includeBuild("common")
includeBuild("datacompiler")
rootProject.name = "BedrockECS"
include("server")
include("game")
include("plugin")
include("filesystem")
include("threading")
include("comm")
include("vanilla")
include("vanilla:generated-base")
include("vanilla:generated")
