// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class ActivatorRailBlockType private constructor(
    public override val runtimeID: Short,
    public val railDataBit: Byte,
    public val railDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(railDataBit: Byte = this.railDataBit, railDirection: Int = this.railDirection):
        ActivatorRailBlockType {
        val e = ActivatorRailBlockType(0.toShort(), railDataBit, railDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: ActivatorRailBlockType): Boolean {
        var ret = true
        ret = ret && (this.railDataBit == other.railDataBit)
        ret = ret && (this.railDirection == other.railDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:activator_rail"

        public override val itemID: ItemID = ItemID(126)

        private lateinit var instance122: ActivatorRailBlockType

        private lateinit var instance123: ActivatorRailBlockType

        private lateinit var instance124: ActivatorRailBlockType

        private lateinit var instance125: ActivatorRailBlockType

        private lateinit var instance126: ActivatorRailBlockType

        private lateinit var instance127: ActivatorRailBlockType

        private lateinit var instance128: ActivatorRailBlockType

        private lateinit var instance129: ActivatorRailBlockType

        private lateinit var instance130: ActivatorRailBlockType

        private lateinit var instance131: ActivatorRailBlockType

        private lateinit var instance132: ActivatorRailBlockType

        private lateinit var instance133: ActivatorRailBlockType

        init {
            init0()
        }

        public override val primary: ActivatorRailBlockType = instance122

        public override val allInstances: List<ActivatorRailBlockType> =
            listOf(instance122, instance123, instance124, instance125, instance126, instance127, instance128, instance129, instance130, instance131, instance132, instance133)

        public fun init0() {
            instance122 = ActivatorRailBlockType(122.toShort(), 0.toByte(), 0)
            instance123 = ActivatorRailBlockType(123.toShort(), 0.toByte(), 1)
            instance124 = ActivatorRailBlockType(124.toShort(), 0.toByte(), 2)
            instance125 = ActivatorRailBlockType(125.toShort(), 0.toByte(), 3)
            instance126 = ActivatorRailBlockType(126.toShort(), 0.toByte(), 4)
            instance127 = ActivatorRailBlockType(127.toShort(), 0.toByte(), 5)
            instance128 = ActivatorRailBlockType(128.toShort(), 1.toByte(), 0)
            instance129 = ActivatorRailBlockType(129.toShort(), 1.toByte(), 1)
            instance130 = ActivatorRailBlockType(130.toShort(), 1.toByte(), 2)
            instance131 = ActivatorRailBlockType(131.toShort(), 1.toByte(), 3)
            instance132 = ActivatorRailBlockType(132.toShort(), 1.toByte(), 4)
            instance133 = ActivatorRailBlockType(133.toShort(), 1.toByte(), 5)
        }
    }
}
