// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class AzaleaBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): AzaleaBlockType {
        val e = AzaleaBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: AzaleaBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:azalea"

        public override val itemID: ItemID = ItemID(-337)

        private lateinit var instance168: AzaleaBlockType

        init {
            init0()
        }

        public override val primary: AzaleaBlockType = instance168

        public override val allInstances: List<AzaleaBlockType> = listOf(instance168)

        public fun init0() {
            instance168 = AzaleaBlockType(168.toShort())
        }
    }
}
