// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class BasaltBlockType private constructor(
    public override val runtimeID: Short,
    public val pillarAxis: String
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(pillarAxis: String = this.pillarAxis): BasaltBlockType {
        val e = BasaltBlockType(0.toShort(), pillarAxis)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: BasaltBlockType): Boolean {
        var ret = true
        ret = ret && (this.pillarAxis == other.pillarAxis)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:basalt"

        public override val itemID: ItemID = ItemID(-234)

        private lateinit var instance214: BasaltBlockType

        private lateinit var instance215: BasaltBlockType

        private lateinit var instance216: BasaltBlockType

        init {
            init0()
        }

        public override val primary: BasaltBlockType = instance214

        public override val allInstances: List<BasaltBlockType> =
            listOf(instance214, instance215, instance216)

        public fun init0() {
            instance214 = BasaltBlockType(214.toShort(), "y")
            instance215 = BasaltBlockType(215.toShort(), "x")
            instance216 = BasaltBlockType(216.toShort(), "z")
        }
    }
}
