// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class BeaconBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): BeaconBlockType {
        val e = BeaconBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: BeaconBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:beacon"

        public override val itemID: ItemID = ItemID(138)

        private lateinit var instance217: BeaconBlockType

        init {
            init0()
        }

        public override val primary: BeaconBlockType = instance217

        public override val allInstances: List<BeaconBlockType> = listOf(instance217)

        public fun init0() {
            instance217 = BeaconBlockType(217.toShort())
        }
    }
}
