// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class BeehiveBlockType private constructor(
    public override val runtimeID: Short,
    public val direction: Int,
    public val honeyLevel: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(direction: Int = this.direction, honeyLevel: Int = this.honeyLevel):
        BeehiveBlockType {
        val e = BeehiveBlockType(0.toShort(), direction, honeyLevel)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: BeehiveBlockType): Boolean {
        var ret = true
        ret = ret && (this.direction == other.direction)
        ret = ret && (this.honeyLevel == other.honeyLevel)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:beehive"

        public override val itemID: ItemID = ItemID(-219)

        private lateinit var instance260: BeehiveBlockType

        private lateinit var instance261: BeehiveBlockType

        private lateinit var instance262: BeehiveBlockType

        private lateinit var instance263: BeehiveBlockType

        private lateinit var instance264: BeehiveBlockType

        private lateinit var instance265: BeehiveBlockType

        private lateinit var instance266: BeehiveBlockType

        private lateinit var instance267: BeehiveBlockType

        private lateinit var instance268: BeehiveBlockType

        private lateinit var instance269: BeehiveBlockType

        private lateinit var instance270: BeehiveBlockType

        private lateinit var instance271: BeehiveBlockType

        private lateinit var instance272: BeehiveBlockType

        private lateinit var instance273: BeehiveBlockType

        private lateinit var instance274: BeehiveBlockType

        private lateinit var instance275: BeehiveBlockType

        private lateinit var instance276: BeehiveBlockType

        private lateinit var instance277: BeehiveBlockType

        private lateinit var instance278: BeehiveBlockType

        private lateinit var instance279: BeehiveBlockType

        private lateinit var instance280: BeehiveBlockType

        private lateinit var instance281: BeehiveBlockType

        private lateinit var instance282: BeehiveBlockType

        private lateinit var instance283: BeehiveBlockType

        init {
            init0()
        }

        public override val primary: BeehiveBlockType = instance260

        public override val allInstances: List<BeehiveBlockType> =
            listOf(instance260, instance261, instance262, instance263, instance264, instance265, instance266, instance267, instance268, instance269, instance270, instance271, instance272, instance273, instance274, instance275, instance276, instance277, instance278, instance279, instance280, instance281, instance282, instance283)

        public fun init0() {
            instance260 = BeehiveBlockType(260.toShort(), 0, 0)
            instance261 = BeehiveBlockType(261.toShort(), 1, 0)
            instance262 = BeehiveBlockType(262.toShort(), 2, 0)
            instance263 = BeehiveBlockType(263.toShort(), 3, 0)
            instance264 = BeehiveBlockType(264.toShort(), 0, 1)
            instance265 = BeehiveBlockType(265.toShort(), 1, 1)
            instance266 = BeehiveBlockType(266.toShort(), 2, 1)
            instance267 = BeehiveBlockType(267.toShort(), 3, 1)
            instance268 = BeehiveBlockType(268.toShort(), 0, 2)
            instance269 = BeehiveBlockType(269.toShort(), 1, 2)
            instance270 = BeehiveBlockType(270.toShort(), 2, 2)
            instance271 = BeehiveBlockType(271.toShort(), 3, 2)
            instance272 = BeehiveBlockType(272.toShort(), 0, 3)
            instance273 = BeehiveBlockType(273.toShort(), 1, 3)
            instance274 = BeehiveBlockType(274.toShort(), 2, 3)
            instance275 = BeehiveBlockType(275.toShort(), 3, 3)
            instance276 = BeehiveBlockType(276.toShort(), 0, 4)
            instance277 = BeehiveBlockType(277.toShort(), 1, 4)
            instance278 = BeehiveBlockType(278.toShort(), 2, 4)
            instance279 = BeehiveBlockType(279.toShort(), 3, 4)
            instance280 = BeehiveBlockType(280.toShort(), 0, 5)
            instance281 = BeehiveBlockType(281.toShort(), 1, 5)
            instance282 = BeehiveBlockType(282.toShort(), 2, 5)
            instance283 = BeehiveBlockType(283.toShort(), 3, 5)
        }
    }
}
