// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class BrickStairsBlockType private constructor(
    public override val runtimeID: Short,
    public val upsideDownBit: Byte,
    public val weirdoDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        upsideDownBit: Byte = this.upsideDownBit,
        weirdoDirection: Int =
            this.weirdoDirection
    ): BrickStairsBlockType {
        val e = BrickStairsBlockType(0.toShort(), upsideDownBit, weirdoDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: BrickStairsBlockType): Boolean {
        var ret = true
        ret = ret && (this.upsideDownBit == other.upsideDownBit)
        ret = ret && (this.weirdoDirection == other.weirdoDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:brick_stairs"

        public override val itemID: ItemID = ItemID(108)

        private lateinit var instance876: BrickStairsBlockType

        private lateinit var instance877: BrickStairsBlockType

        private lateinit var instance878: BrickStairsBlockType

        private lateinit var instance879: BrickStairsBlockType

        private lateinit var instance880: BrickStairsBlockType

        private lateinit var instance881: BrickStairsBlockType

        private lateinit var instance882: BrickStairsBlockType

        private lateinit var instance883: BrickStairsBlockType

        init {
            init0()
        }

        public override val primary: BrickStairsBlockType = instance876

        public override val allInstances: List<BrickStairsBlockType> =
            listOf(instance876, instance877, instance878, instance879, instance880, instance881, instance882, instance883)

        public fun init0() {
            instance876 = BrickStairsBlockType(876.toShort(), 0.toByte(), 0)
            instance877 = BrickStairsBlockType(877.toShort(), 0.toByte(), 1)
            instance878 = BrickStairsBlockType(878.toShort(), 0.toByte(), 2)
            instance879 = BrickStairsBlockType(879.toShort(), 0.toByte(), 3)
            instance880 = BrickStairsBlockType(880.toShort(), 1.toByte(), 0)
            instance881 = BrickStairsBlockType(881.toShort(), 1.toByte(), 1)
            instance882 = BrickStairsBlockType(882.toShort(), 1.toByte(), 2)
            instance883 = BrickStairsBlockType(883.toShort(), 1.toByte(), 3)
        }
    }
}
