// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class BuddingAmethystBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): BuddingAmethystBlockType {
        val e = BuddingAmethystBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: BuddingAmethystBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:budding_amethyst"

        public override val itemID: ItemID = ItemID(-328)

        private lateinit var instance919: BuddingAmethystBlockType

        init {
            init0()
        }

        public override val primary: BuddingAmethystBlockType = instance919

        public override val allInstances: List<BuddingAmethystBlockType> = listOf(instance919)

        public fun init0() {
            instance919 = BuddingAmethystBlockType(919.toShort())
        }
    }
}
