// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class CarpetBlockType private constructor(
    public override val runtimeID: Short,
    public val color: String
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(color: String = this.color): CarpetBlockType {
        val e = CarpetBlockType(0.toShort(), color)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: CarpetBlockType): Boolean {
        var ret = true
        ret = ret && (this.color == other.color)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:carpet"

        public override val itemID: ItemID = ItemID(171)

        private lateinit var instance963: CarpetBlockType

        private lateinit var instance964: CarpetBlockType

        private lateinit var instance965: CarpetBlockType

        private lateinit var instance966: CarpetBlockType

        private lateinit var instance967: CarpetBlockType

        private lateinit var instance968: CarpetBlockType

        private lateinit var instance969: CarpetBlockType

        private lateinit var instance970: CarpetBlockType

        private lateinit var instance971: CarpetBlockType

        private lateinit var instance972: CarpetBlockType

        private lateinit var instance973: CarpetBlockType

        private lateinit var instance974: CarpetBlockType

        private lateinit var instance975: CarpetBlockType

        private lateinit var instance976: CarpetBlockType

        private lateinit var instance977: CarpetBlockType

        private lateinit var instance978: CarpetBlockType

        init {
            init0()
        }

        public override val primary: CarpetBlockType = instance963

        public override val allInstances: List<CarpetBlockType> =
            listOf(instance963, instance964, instance965, instance966, instance967, instance968, instance969, instance970, instance971, instance972, instance973, instance974, instance975, instance976, instance977, instance978)

        public fun init0() {
            instance963 = CarpetBlockType(963.toShort(), "white")
            instance964 = CarpetBlockType(964.toShort(), "orange")
            instance965 = CarpetBlockType(965.toShort(), "magenta")
            instance966 = CarpetBlockType(966.toShort(), "light_blue")
            instance967 = CarpetBlockType(967.toShort(), "yellow")
            instance968 = CarpetBlockType(968.toShort(), "lime")
            instance969 = CarpetBlockType(969.toShort(), "pink")
            instance970 = CarpetBlockType(970.toShort(), "gray")
            instance971 = CarpetBlockType(971.toShort(), "silver")
            instance972 = CarpetBlockType(972.toShort(), "cyan")
            instance973 = CarpetBlockType(973.toShort(), "purple")
            instance974 = CarpetBlockType(974.toShort(), "blue")
            instance975 = CarpetBlockType(975.toShort(), "brown")
            instance976 = CarpetBlockType(976.toShort(), "green")
            instance977 = CarpetBlockType(977.toShort(), "red")
            instance978 = CarpetBlockType(978.toShort(), "black")
        }
    }
}
