// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class CaveVinesHeadWithBerriesBlockType private constructor(
    public override val runtimeID: Short,
    public val growingPlantAge: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(growingPlantAge: Int = this.growingPlantAge): CaveVinesHeadWithBerriesBlockType {
        val e = CaveVinesHeadWithBerriesBlockType(0.toShort(), growingPlantAge)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: CaveVinesHeadWithBerriesBlockType): Boolean {
        var ret = true
        ret = ret && (this.growingPlantAge == other.growingPlantAge)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:cave_vines_head_with_berries"

        public override val itemID: ItemID = ItemID(-376)

        private lateinit var instance1065: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1066: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1067: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1068: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1069: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1070: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1071: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1072: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1073: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1074: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1075: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1076: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1077: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1078: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1079: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1080: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1081: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1082: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1083: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1084: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1085: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1086: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1087: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1088: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1089: CaveVinesHeadWithBerriesBlockType

        private lateinit var instance1090: CaveVinesHeadWithBerriesBlockType

        init {
            init0()
        }

        public override val primary: CaveVinesHeadWithBerriesBlockType = instance1065

        public override val allInstances: List<CaveVinesHeadWithBerriesBlockType> =
            listOf(instance1065, instance1066, instance1067, instance1068, instance1069, instance1070, instance1071, instance1072, instance1073, instance1074, instance1075, instance1076, instance1077, instance1078, instance1079, instance1080, instance1081, instance1082, instance1083, instance1084, instance1085, instance1086, instance1087, instance1088, instance1089, instance1090)

        public fun init0() {
            instance1065 = CaveVinesHeadWithBerriesBlockType(1065.toShort(), 0)
            instance1066 = CaveVinesHeadWithBerriesBlockType(1066.toShort(), 1)
            instance1067 = CaveVinesHeadWithBerriesBlockType(1067.toShort(), 2)
            instance1068 = CaveVinesHeadWithBerriesBlockType(1068.toShort(), 3)
            instance1069 = CaveVinesHeadWithBerriesBlockType(1069.toShort(), 4)
            instance1070 = CaveVinesHeadWithBerriesBlockType(1070.toShort(), 5)
            instance1071 = CaveVinesHeadWithBerriesBlockType(1071.toShort(), 6)
            instance1072 = CaveVinesHeadWithBerriesBlockType(1072.toShort(), 7)
            instance1073 = CaveVinesHeadWithBerriesBlockType(1073.toShort(), 8)
            instance1074 = CaveVinesHeadWithBerriesBlockType(1074.toShort(), 9)
            instance1075 = CaveVinesHeadWithBerriesBlockType(1075.toShort(), 10)
            instance1076 = CaveVinesHeadWithBerriesBlockType(1076.toShort(), 11)
            instance1077 = CaveVinesHeadWithBerriesBlockType(1077.toShort(), 12)
            instance1078 = CaveVinesHeadWithBerriesBlockType(1078.toShort(), 13)
            instance1079 = CaveVinesHeadWithBerriesBlockType(1079.toShort(), 14)
            instance1080 = CaveVinesHeadWithBerriesBlockType(1080.toShort(), 15)
            instance1081 = CaveVinesHeadWithBerriesBlockType(1081.toShort(), 16)
            instance1082 = CaveVinesHeadWithBerriesBlockType(1082.toShort(), 17)
            instance1083 = CaveVinesHeadWithBerriesBlockType(1083.toShort(), 18)
            instance1084 = CaveVinesHeadWithBerriesBlockType(1084.toShort(), 19)
            instance1085 = CaveVinesHeadWithBerriesBlockType(1085.toShort(), 20)
            instance1086 = CaveVinesHeadWithBerriesBlockType(1086.toShort(), 21)
            instance1087 = CaveVinesHeadWithBerriesBlockType(1087.toShort(), 22)
            instance1088 = CaveVinesHeadWithBerriesBlockType(1088.toShort(), 23)
            instance1089 = CaveVinesHeadWithBerriesBlockType(1089.toShort(), 24)
            instance1090 = CaveVinesHeadWithBerriesBlockType(1090.toShort(), 25)
        }
    }
}
