// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class ChainCommandBlockBlockType private constructor(
    public override val runtimeID: Short,
    public val conditionalBit: Byte,
    public val facingDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        conditionalBit: Byte = this.conditionalBit,
        facingDirection: Int =
            this.facingDirection
    ): ChainCommandBlockBlockType {
        val e = ChainCommandBlockBlockType(0.toShort(), conditionalBit, facingDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: ChainCommandBlockBlockType): Boolean {
        var ret = true
        ret = ret && (this.conditionalBit == other.conditionalBit)
        ret = ret && (this.facingDirection == other.facingDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:chain_command_block"

        public override val itemID: ItemID = ItemID(189)

        private lateinit var instance1094: ChainCommandBlockBlockType

        private lateinit var instance1095: ChainCommandBlockBlockType

        private lateinit var instance1096: ChainCommandBlockBlockType

        private lateinit var instance1097: ChainCommandBlockBlockType

        private lateinit var instance1098: ChainCommandBlockBlockType

        private lateinit var instance1099: ChainCommandBlockBlockType

        private lateinit var instance1100: ChainCommandBlockBlockType

        private lateinit var instance1101: ChainCommandBlockBlockType

        private lateinit var instance1102: ChainCommandBlockBlockType

        private lateinit var instance1103: ChainCommandBlockBlockType

        private lateinit var instance1104: ChainCommandBlockBlockType

        private lateinit var instance1105: ChainCommandBlockBlockType

        init {
            init0()
        }

        public override val primary: ChainCommandBlockBlockType = instance1094

        public override val allInstances: List<ChainCommandBlockBlockType> =
            listOf(instance1094, instance1095, instance1096, instance1097, instance1098, instance1099, instance1100, instance1101, instance1102, instance1103, instance1104, instance1105)

        public fun init0() {
            instance1094 = ChainCommandBlockBlockType(1094.toShort(), 0.toByte(), 0)
            instance1095 = ChainCommandBlockBlockType(1095.toShort(), 0.toByte(), 1)
            instance1096 = ChainCommandBlockBlockType(1096.toShort(), 0.toByte(), 2)
            instance1097 = ChainCommandBlockBlockType(1097.toShort(), 0.toByte(), 3)
            instance1098 = ChainCommandBlockBlockType(1098.toShort(), 0.toByte(), 4)
            instance1099 = ChainCommandBlockBlockType(1099.toShort(), 0.toByte(), 5)
            instance1100 = ChainCommandBlockBlockType(1100.toShort(), 1.toByte(), 0)
            instance1101 = ChainCommandBlockBlockType(1101.toShort(), 1.toByte(), 1)
            instance1102 = ChainCommandBlockBlockType(1102.toShort(), 1.toByte(), 2)
            instance1103 = ChainCommandBlockBlockType(1103.toShort(), 1.toByte(), 3)
            instance1104 = ChainCommandBlockBlockType(1104.toShort(), 1.toByte(), 4)
            instance1105 = ChainCommandBlockBlockType(1105.toShort(), 1.toByte(), 5)
        }
    }
}
