// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class ChiseledNetherBricksBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): ChiseledNetherBricksBlockType {
        val e = ChiseledNetherBricksBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: ChiseledNetherBricksBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:chiseled_nether_bricks"

        public override val itemID: ItemID = ItemID(-302)

        private lateinit var instance1130: ChiseledNetherBricksBlockType

        init {
            init0()
        }

        public override val primary: ChiseledNetherBricksBlockType = instance1130

        public override val allInstances: List<ChiseledNetherBricksBlockType> = listOf(instance1130)

        public fun init0() {
            instance1130 = ChiseledNetherBricksBlockType(1130.toShort())
        }
    }
}
