// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class CoalOreBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): CoalOreBlockType {
        val e = CoalOreBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: CoalOreBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:coal_ore"

        public override val itemID: ItemID = ItemID(16)

        private lateinit var instance1142: CoalOreBlockType

        init {
            init0()
        }

        public override val primary: CoalOreBlockType = instance1142

        public override val allInstances: List<CoalOreBlockType> = listOf(instance1142)

        public fun init0() {
            instance1142 = CoalOreBlockType(1142.toShort())
        }
    }
}
