// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class ComposterBlockType private constructor(
    public override val runtimeID: Short,
    public val composterFillLevel: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(composterFillLevel: Int = this.composterFillLevel): ComposterBlockType {
        val e = ComposterBlockType(0.toShort(), composterFillLevel)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: ComposterBlockType): Boolean {
        var ret = true
        ret = ret && (this.composterFillLevel == other.composterFillLevel)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:composter"

        public override val itemID: ItemID = ItemID(-213)

        private lateinit var instance3635: ComposterBlockType

        private lateinit var instance3636: ComposterBlockType

        private lateinit var instance3637: ComposterBlockType

        private lateinit var instance3638: ComposterBlockType

        private lateinit var instance3639: ComposterBlockType

        private lateinit var instance3640: ComposterBlockType

        private lateinit var instance3641: ComposterBlockType

        private lateinit var instance3642: ComposterBlockType

        private lateinit var instance3643: ComposterBlockType

        init {
            init0()
        }

        public override val primary: ComposterBlockType = instance3635

        public override val allInstances: List<ComposterBlockType> =
            listOf(instance3635, instance3636, instance3637, instance3638, instance3639, instance3640, instance3641, instance3642, instance3643)

        public fun init0() {
            instance3635 = ComposterBlockType(3635.toShort(), 0)
            instance3636 = ComposterBlockType(3636.toShort(), 1)
            instance3637 = ComposterBlockType(3637.toShort(), 2)
            instance3638 = ComposterBlockType(3638.toShort(), 3)
            instance3639 = ComposterBlockType(3639.toShort(), 4)
            instance3640 = ComposterBlockType(3640.toShort(), 5)
            instance3641 = ComposterBlockType(3641.toShort(), 6)
            instance3642 = ComposterBlockType(3642.toShort(), 7)
            instance3643 = ComposterBlockType(3643.toShort(), 8)
        }
    }
}
