// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class ConcretePowderBlockType private constructor(
    public override val runtimeID: Short,
    public val color: String
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(color: String = this.color): ConcretePowderBlockType {
        val e = ConcretePowderBlockType(0.toShort(), color)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: ConcretePowderBlockType): Boolean {
        var ret = true
        ret = ret && (this.color == other.color)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:concretePowder"

        public override val itemID: ItemID = ItemID(237)

        private lateinit var instance3660: ConcretePowderBlockType

        private lateinit var instance3661: ConcretePowderBlockType

        private lateinit var instance3662: ConcretePowderBlockType

        private lateinit var instance3663: ConcretePowderBlockType

        private lateinit var instance3664: ConcretePowderBlockType

        private lateinit var instance3665: ConcretePowderBlockType

        private lateinit var instance3666: ConcretePowderBlockType

        private lateinit var instance3667: ConcretePowderBlockType

        private lateinit var instance3668: ConcretePowderBlockType

        private lateinit var instance3669: ConcretePowderBlockType

        private lateinit var instance3670: ConcretePowderBlockType

        private lateinit var instance3671: ConcretePowderBlockType

        private lateinit var instance3672: ConcretePowderBlockType

        private lateinit var instance3673: ConcretePowderBlockType

        private lateinit var instance3674: ConcretePowderBlockType

        private lateinit var instance3675: ConcretePowderBlockType

        init {
            init0()
        }

        public override val primary: ConcretePowderBlockType = instance3660

        public override val allInstances: List<ConcretePowderBlockType> =
            listOf(instance3660, instance3661, instance3662, instance3663, instance3664, instance3665, instance3666, instance3667, instance3668, instance3669, instance3670, instance3671, instance3672, instance3673, instance3674, instance3675)

        public fun init0() {
            instance3660 = ConcretePowderBlockType(3660.toShort(), "white")
            instance3661 = ConcretePowderBlockType(3661.toShort(), "orange")
            instance3662 = ConcretePowderBlockType(3662.toShort(), "magenta")
            instance3663 = ConcretePowderBlockType(3663.toShort(), "light_blue")
            instance3664 = ConcretePowderBlockType(3664.toShort(), "yellow")
            instance3665 = ConcretePowderBlockType(3665.toShort(), "lime")
            instance3666 = ConcretePowderBlockType(3666.toShort(), "pink")
            instance3667 = ConcretePowderBlockType(3667.toShort(), "gray")
            instance3668 = ConcretePowderBlockType(3668.toShort(), "silver")
            instance3669 = ConcretePowderBlockType(3669.toShort(), "cyan")
            instance3670 = ConcretePowderBlockType(3670.toShort(), "purple")
            instance3671 = ConcretePowderBlockType(3671.toShort(), "blue")
            instance3672 = ConcretePowderBlockType(3672.toShort(), "brown")
            instance3673 = ConcretePowderBlockType(3673.toShort(), "green")
            instance3674 = ConcretePowderBlockType(3674.toShort(), "red")
            instance3675 = ConcretePowderBlockType(3675.toShort(), "black")
        }
    }
}
