// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class CrimsonFenceGateBlockType private constructor(
    public override val runtimeID: Short,
    public val direction: Int,
    public val inWallBit: Byte,
    public val openBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        direction: Int = this.direction,
        inWallBit: Byte = this.inWallBit,
        openBit: Byte = this.openBit
    ): CrimsonFenceGateBlockType {
        val e = CrimsonFenceGateBlockType(0.toShort(), direction, inWallBit, openBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: CrimsonFenceGateBlockType): Boolean {
        var ret = true
        ret = ret && (this.direction == other.direction)
        ret = ret && (this.inWallBit == other.inWallBit)
        ret = ret && (this.openBit == other.openBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:crimson_fence_gate"

        public override val itemID: ItemID = ItemID(-258)

        private lateinit var instance3819: CrimsonFenceGateBlockType

        private lateinit var instance3820: CrimsonFenceGateBlockType

        private lateinit var instance3821: CrimsonFenceGateBlockType

        private lateinit var instance3822: CrimsonFenceGateBlockType

        private lateinit var instance3823: CrimsonFenceGateBlockType

        private lateinit var instance3824: CrimsonFenceGateBlockType

        private lateinit var instance3825: CrimsonFenceGateBlockType

        private lateinit var instance3826: CrimsonFenceGateBlockType

        private lateinit var instance3827: CrimsonFenceGateBlockType

        private lateinit var instance3828: CrimsonFenceGateBlockType

        private lateinit var instance3829: CrimsonFenceGateBlockType

        private lateinit var instance3830: CrimsonFenceGateBlockType

        private lateinit var instance3831: CrimsonFenceGateBlockType

        private lateinit var instance3832: CrimsonFenceGateBlockType

        private lateinit var instance3833: CrimsonFenceGateBlockType

        private lateinit var instance3834: CrimsonFenceGateBlockType

        init {
            init0()
        }

        public override val primary: CrimsonFenceGateBlockType = instance3819

        public override val allInstances: List<CrimsonFenceGateBlockType> =
            listOf(instance3819, instance3820, instance3821, instance3822, instance3823, instance3824, instance3825, instance3826, instance3827, instance3828, instance3829, instance3830, instance3831, instance3832, instance3833, instance3834)

        public fun init0() {
            instance3819 = CrimsonFenceGateBlockType(3819.toShort(), 0, 0.toByte(), 0.toByte())
            instance3820 = CrimsonFenceGateBlockType(3820.toShort(), 1, 0.toByte(), 0.toByte())
            instance3821 = CrimsonFenceGateBlockType(3821.toShort(), 2, 0.toByte(), 0.toByte())
            instance3822 = CrimsonFenceGateBlockType(3822.toShort(), 3, 0.toByte(), 0.toByte())
            instance3823 = CrimsonFenceGateBlockType(3823.toShort(), 0, 0.toByte(), 1.toByte())
            instance3824 = CrimsonFenceGateBlockType(3824.toShort(), 1, 0.toByte(), 1.toByte())
            instance3825 = CrimsonFenceGateBlockType(3825.toShort(), 2, 0.toByte(), 1.toByte())
            instance3826 = CrimsonFenceGateBlockType(3826.toShort(), 3, 0.toByte(), 1.toByte())
            instance3827 = CrimsonFenceGateBlockType(3827.toShort(), 0, 1.toByte(), 0.toByte())
            instance3828 = CrimsonFenceGateBlockType(3828.toShort(), 1, 1.toByte(), 0.toByte())
            instance3829 = CrimsonFenceGateBlockType(3829.toShort(), 2, 1.toByte(), 0.toByte())
            instance3830 = CrimsonFenceGateBlockType(3830.toShort(), 3, 1.toByte(), 0.toByte())
            instance3831 = CrimsonFenceGateBlockType(3831.toShort(), 0, 1.toByte(), 1.toByte())
            instance3832 = CrimsonFenceGateBlockType(3832.toShort(), 1, 1.toByte(), 1.toByte())
            instance3833 = CrimsonFenceGateBlockType(3833.toShort(), 2, 1.toByte(), 1.toByte())
            instance3834 = CrimsonFenceGateBlockType(3834.toShort(), 3, 1.toByte(), 1.toByte())
        }
    }
}
