// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class CrimsonButtonBlockType private constructor(
    public override val runtimeID: Short,
    public val buttonPressedBit: Byte,
    public val facingDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        buttonPressedBit: Byte = this.buttonPressedBit,
        facingDirection: Int =
            this.facingDirection
    ): CrimsonButtonBlockType {
        val e = CrimsonButtonBlockType(0.toShort(), buttonPressedBit, facingDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: CrimsonButtonBlockType): Boolean {
        var ret = true
        ret = ret && (this.buttonPressedBit == other.buttonPressedBit)
        ret = ret && (this.facingDirection == other.facingDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:crimson_button"

        public override val itemID: ItemID = ItemID(-260)

        private lateinit var instance3772: CrimsonButtonBlockType

        private lateinit var instance3773: CrimsonButtonBlockType

        private lateinit var instance3774: CrimsonButtonBlockType

        private lateinit var instance3775: CrimsonButtonBlockType

        private lateinit var instance3776: CrimsonButtonBlockType

        private lateinit var instance3777: CrimsonButtonBlockType

        private lateinit var instance3778: CrimsonButtonBlockType

        private lateinit var instance3779: CrimsonButtonBlockType

        private lateinit var instance3780: CrimsonButtonBlockType

        private lateinit var instance3781: CrimsonButtonBlockType

        private lateinit var instance3782: CrimsonButtonBlockType

        private lateinit var instance3783: CrimsonButtonBlockType

        init {
            init0()
        }

        public override val primary: CrimsonButtonBlockType = instance3772

        public override val allInstances: List<CrimsonButtonBlockType> =
            listOf(instance3772, instance3773, instance3774, instance3775, instance3776, instance3777, instance3778, instance3779, instance3780, instance3781, instance3782, instance3783)

        public fun init0() {
            instance3772 = CrimsonButtonBlockType(3772.toShort(), 0.toByte(), 0)
            instance3773 = CrimsonButtonBlockType(3773.toShort(), 0.toByte(), 1)
            instance3774 = CrimsonButtonBlockType(3774.toShort(), 0.toByte(), 2)
            instance3775 = CrimsonButtonBlockType(3775.toShort(), 0.toByte(), 3)
            instance3776 = CrimsonButtonBlockType(3776.toShort(), 0.toByte(), 4)
            instance3777 = CrimsonButtonBlockType(3777.toShort(), 0.toByte(), 5)
            instance3778 = CrimsonButtonBlockType(3778.toShort(), 1.toByte(), 0)
            instance3779 = CrimsonButtonBlockType(3779.toShort(), 1.toByte(), 1)
            instance3780 = CrimsonButtonBlockType(3780.toShort(), 1.toByte(), 2)
            instance3781 = CrimsonButtonBlockType(3781.toShort(), 1.toByte(), 3)
            instance3782 = CrimsonButtonBlockType(3782.toShort(), 1.toByte(), 4)
            instance3783 = CrimsonButtonBlockType(3783.toShort(), 1.toByte(), 5)
        }
    }
}
