// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DarkOakFenceGateBlockType private constructor(
    public override val runtimeID: Short,
    public val direction: Int,
    public val inWallBit: Byte,
    public val openBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        direction: Int = this.direction,
        inWallBit: Byte = this.inWallBit,
        openBit: Byte = this.openBit
    ): DarkOakFenceGateBlockType {
        val e = DarkOakFenceGateBlockType(0.toShort(), direction, inWallBit, openBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DarkOakFenceGateBlockType): Boolean {
        var ret = true
        ret = ret && (this.direction == other.direction)
        ret = ret && (this.inWallBit == other.inWallBit)
        ret = ret && (this.openBit == other.openBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:dark_oak_fence_gate"

        public override val itemID: ItemID = ItemID(186)

        private lateinit var instance3981: DarkOakFenceGateBlockType

        private lateinit var instance3982: DarkOakFenceGateBlockType

        private lateinit var instance3983: DarkOakFenceGateBlockType

        private lateinit var instance3984: DarkOakFenceGateBlockType

        private lateinit var instance3985: DarkOakFenceGateBlockType

        private lateinit var instance3986: DarkOakFenceGateBlockType

        private lateinit var instance3987: DarkOakFenceGateBlockType

        private lateinit var instance3988: DarkOakFenceGateBlockType

        private lateinit var instance3989: DarkOakFenceGateBlockType

        private lateinit var instance3990: DarkOakFenceGateBlockType

        private lateinit var instance3991: DarkOakFenceGateBlockType

        private lateinit var instance3992: DarkOakFenceGateBlockType

        private lateinit var instance3993: DarkOakFenceGateBlockType

        private lateinit var instance3994: DarkOakFenceGateBlockType

        private lateinit var instance3995: DarkOakFenceGateBlockType

        private lateinit var instance3996: DarkOakFenceGateBlockType

        init {
            init0()
        }

        public override val primary: DarkOakFenceGateBlockType = instance3981

        public override val allInstances: List<DarkOakFenceGateBlockType> =
            listOf(instance3981, instance3982, instance3983, instance3984, instance3985, instance3986, instance3987, instance3988, instance3989, instance3990, instance3991, instance3992, instance3993, instance3994, instance3995, instance3996)

        public fun init0() {
            instance3981 = DarkOakFenceGateBlockType(3981.toShort(), 0, 0.toByte(), 0.toByte())
            instance3982 = DarkOakFenceGateBlockType(3982.toShort(), 1, 0.toByte(), 0.toByte())
            instance3983 = DarkOakFenceGateBlockType(3983.toShort(), 2, 0.toByte(), 0.toByte())
            instance3984 = DarkOakFenceGateBlockType(3984.toShort(), 3, 0.toByte(), 0.toByte())
            instance3985 = DarkOakFenceGateBlockType(3985.toShort(), 0, 0.toByte(), 1.toByte())
            instance3986 = DarkOakFenceGateBlockType(3986.toShort(), 1, 0.toByte(), 1.toByte())
            instance3987 = DarkOakFenceGateBlockType(3987.toShort(), 2, 0.toByte(), 1.toByte())
            instance3988 = DarkOakFenceGateBlockType(3988.toShort(), 3, 0.toByte(), 1.toByte())
            instance3989 = DarkOakFenceGateBlockType(3989.toShort(), 0, 1.toByte(), 0.toByte())
            instance3990 = DarkOakFenceGateBlockType(3990.toShort(), 1, 1.toByte(), 0.toByte())
            instance3991 = DarkOakFenceGateBlockType(3991.toShort(), 2, 1.toByte(), 0.toByte())
            instance3992 = DarkOakFenceGateBlockType(3992.toShort(), 3, 1.toByte(), 0.toByte())
            instance3993 = DarkOakFenceGateBlockType(3993.toShort(), 0, 1.toByte(), 1.toByte())
            instance3994 = DarkOakFenceGateBlockType(3994.toShort(), 1, 1.toByte(), 1.toByte())
            instance3995 = DarkOakFenceGateBlockType(3995.toShort(), 2, 1.toByte(), 1.toByte())
            instance3996 = DarkOakFenceGateBlockType(3996.toShort(), 3, 1.toByte(), 1.toByte())
        }
    }
}
