// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DarkOakTrapdoorBlockType private constructor(
    public override val runtimeID: Short,
    public val direction: Int,
    public val openBit: Byte,
    public val upsideDownBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        direction: Int = this.direction,
        openBit: Byte = this.openBit,
        upsideDownBit: Byte = this.upsideDownBit
    ): DarkOakTrapdoorBlockType {
        val e = DarkOakTrapdoorBlockType(0.toShort(), direction, openBit, upsideDownBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DarkOakTrapdoorBlockType): Boolean {
        var ret = true
        ret = ret && (this.direction == other.direction)
        ret = ret && (this.openBit == other.openBit)
        ret = ret && (this.upsideDownBit == other.upsideDownBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:dark_oak_trapdoor"

        public override val itemID: ItemID = ItemID(-147)

        private lateinit var instance4021: DarkOakTrapdoorBlockType

        private lateinit var instance4022: DarkOakTrapdoorBlockType

        private lateinit var instance4023: DarkOakTrapdoorBlockType

        private lateinit var instance4024: DarkOakTrapdoorBlockType

        private lateinit var instance4025: DarkOakTrapdoorBlockType

        private lateinit var instance4026: DarkOakTrapdoorBlockType

        private lateinit var instance4027: DarkOakTrapdoorBlockType

        private lateinit var instance4028: DarkOakTrapdoorBlockType

        private lateinit var instance4029: DarkOakTrapdoorBlockType

        private lateinit var instance4030: DarkOakTrapdoorBlockType

        private lateinit var instance4031: DarkOakTrapdoorBlockType

        private lateinit var instance4032: DarkOakTrapdoorBlockType

        private lateinit var instance4033: DarkOakTrapdoorBlockType

        private lateinit var instance4034: DarkOakTrapdoorBlockType

        private lateinit var instance4035: DarkOakTrapdoorBlockType

        private lateinit var instance4036: DarkOakTrapdoorBlockType

        init {
            init0()
        }

        public override val primary: DarkOakTrapdoorBlockType = instance4021

        public override val allInstances: List<DarkOakTrapdoorBlockType> =
            listOf(instance4021, instance4022, instance4023, instance4024, instance4025, instance4026, instance4027, instance4028, instance4029, instance4030, instance4031, instance4032, instance4033, instance4034, instance4035, instance4036)

        public fun init0() {
            instance4021 = DarkOakTrapdoorBlockType(4021.toShort(), 0, 0.toByte(), 0.toByte())
            instance4022 = DarkOakTrapdoorBlockType(4022.toShort(), 1, 0.toByte(), 0.toByte())
            instance4023 = DarkOakTrapdoorBlockType(4023.toShort(), 2, 0.toByte(), 0.toByte())
            instance4024 = DarkOakTrapdoorBlockType(4024.toShort(), 3, 0.toByte(), 0.toByte())
            instance4025 = DarkOakTrapdoorBlockType(4025.toShort(), 0, 0.toByte(), 1.toByte())
            instance4026 = DarkOakTrapdoorBlockType(4026.toShort(), 1, 0.toByte(), 1.toByte())
            instance4027 = DarkOakTrapdoorBlockType(4027.toShort(), 2, 0.toByte(), 1.toByte())
            instance4028 = DarkOakTrapdoorBlockType(4028.toShort(), 3, 0.toByte(), 1.toByte())
            instance4029 = DarkOakTrapdoorBlockType(4029.toShort(), 0, 1.toByte(), 0.toByte())
            instance4030 = DarkOakTrapdoorBlockType(4030.toShort(), 1, 1.toByte(), 0.toByte())
            instance4031 = DarkOakTrapdoorBlockType(4031.toShort(), 2, 1.toByte(), 0.toByte())
            instance4032 = DarkOakTrapdoorBlockType(4032.toShort(), 3, 1.toByte(), 0.toByte())
            instance4033 = DarkOakTrapdoorBlockType(4033.toShort(), 0, 1.toByte(), 1.toByte())
            instance4034 = DarkOakTrapdoorBlockType(4034.toShort(), 1, 1.toByte(), 1.toByte())
            instance4035 = DarkOakTrapdoorBlockType(4035.toShort(), 2, 1.toByte(), 1.toByte())
            instance4036 = DarkOakTrapdoorBlockType(4036.toShort(), 3, 1.toByte(), 1.toByte())
        }
    }
}
