// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DarkOakDoorBlockType private constructor(
    public override val runtimeID: Short,
    public val direction: Int,
    public val doorHingeBit: Byte,
    public val openBit: Byte,
    public val upperBlockBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        direction: Int = this.direction,
        doorHingeBit: Byte = this.doorHingeBit,
        openBit: Byte = this.openBit,
        upperBlockBit: Byte = this.upperBlockBit
    ): DarkOakDoorBlockType {
        val e = DarkOakDoorBlockType(0.toShort(), direction, doorHingeBit, openBit, upperBlockBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DarkOakDoorBlockType): Boolean {
        var ret = true
        ret = ret && (this.direction == other.direction)
        ret = ret && (this.doorHingeBit == other.doorHingeBit)
        ret = ret && (this.openBit == other.openBit)
        ret = ret && (this.upperBlockBit == other.upperBlockBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:dark_oak_door"

        public override val itemID: ItemID = ItemID(197)

        private lateinit var instance3949: DarkOakDoorBlockType

        private lateinit var instance3950: DarkOakDoorBlockType

        private lateinit var instance3951: DarkOakDoorBlockType

        private lateinit var instance3952: DarkOakDoorBlockType

        private lateinit var instance3953: DarkOakDoorBlockType

        private lateinit var instance3954: DarkOakDoorBlockType

        private lateinit var instance3955: DarkOakDoorBlockType

        private lateinit var instance3956: DarkOakDoorBlockType

        private lateinit var instance3957: DarkOakDoorBlockType

        private lateinit var instance3958: DarkOakDoorBlockType

        private lateinit var instance3959: DarkOakDoorBlockType

        private lateinit var instance3960: DarkOakDoorBlockType

        private lateinit var instance3961: DarkOakDoorBlockType

        private lateinit var instance3962: DarkOakDoorBlockType

        private lateinit var instance3963: DarkOakDoorBlockType

        private lateinit var instance3964: DarkOakDoorBlockType

        private lateinit var instance3965: DarkOakDoorBlockType

        private lateinit var instance3966: DarkOakDoorBlockType

        private lateinit var instance3967: DarkOakDoorBlockType

        private lateinit var instance3968: DarkOakDoorBlockType

        private lateinit var instance3969: DarkOakDoorBlockType

        private lateinit var instance3970: DarkOakDoorBlockType

        private lateinit var instance3971: DarkOakDoorBlockType

        private lateinit var instance3972: DarkOakDoorBlockType

        private lateinit var instance3973: DarkOakDoorBlockType

        private lateinit var instance3974: DarkOakDoorBlockType

        private lateinit var instance3975: DarkOakDoorBlockType

        private lateinit var instance3976: DarkOakDoorBlockType

        private lateinit var instance3977: DarkOakDoorBlockType

        private lateinit var instance3978: DarkOakDoorBlockType

        private lateinit var instance3979: DarkOakDoorBlockType

        private lateinit var instance3980: DarkOakDoorBlockType

        init {
            init0()
        }

        public override val primary: DarkOakDoorBlockType = instance3949

        public override val allInstances: List<DarkOakDoorBlockType> =
            listOf(instance3949, instance3950, instance3951, instance3952, instance3953, instance3954, instance3955, instance3956, instance3957, instance3958, instance3959, instance3960, instance3961, instance3962, instance3963, instance3964, instance3965, instance3966, instance3967, instance3968, instance3969, instance3970, instance3971, instance3972, instance3973, instance3974, instance3975, instance3976, instance3977, instance3978, instance3979, instance3980)

        public fun init0() {
            instance3949 = DarkOakDoorBlockType(3949.toShort(), 0, 0.toByte(), 0.toByte(), 0.toByte())
            instance3950 = DarkOakDoorBlockType(3950.toShort(), 1, 0.toByte(), 0.toByte(), 0.toByte())
            instance3951 = DarkOakDoorBlockType(3951.toShort(), 2, 0.toByte(), 0.toByte(), 0.toByte())
            instance3952 = DarkOakDoorBlockType(3952.toShort(), 3, 0.toByte(), 0.toByte(), 0.toByte())
            instance3953 = DarkOakDoorBlockType(3953.toShort(), 0, 0.toByte(), 1.toByte(), 0.toByte())
            instance3954 = DarkOakDoorBlockType(3954.toShort(), 1, 0.toByte(), 1.toByte(), 0.toByte())
            instance3955 = DarkOakDoorBlockType(3955.toShort(), 2, 0.toByte(), 1.toByte(), 0.toByte())
            instance3956 = DarkOakDoorBlockType(3956.toShort(), 3, 0.toByte(), 1.toByte(), 0.toByte())
            instance3957 = DarkOakDoorBlockType(3957.toShort(), 0, 0.toByte(), 0.toByte(), 1.toByte())
            instance3958 = DarkOakDoorBlockType(3958.toShort(), 1, 0.toByte(), 0.toByte(), 1.toByte())
            instance3959 = DarkOakDoorBlockType(3959.toShort(), 2, 0.toByte(), 0.toByte(), 1.toByte())
            instance3960 = DarkOakDoorBlockType(3960.toShort(), 3, 0.toByte(), 0.toByte(), 1.toByte())
            instance3961 = DarkOakDoorBlockType(3961.toShort(), 0, 0.toByte(), 1.toByte(), 1.toByte())
            instance3962 = DarkOakDoorBlockType(3962.toShort(), 1, 0.toByte(), 1.toByte(), 1.toByte())
            instance3963 = DarkOakDoorBlockType(3963.toShort(), 2, 0.toByte(), 1.toByte(), 1.toByte())
            instance3964 = DarkOakDoorBlockType(3964.toShort(), 3, 0.toByte(), 1.toByte(), 1.toByte())
            instance3965 = DarkOakDoorBlockType(3965.toShort(), 0, 1.toByte(), 0.toByte(), 0.toByte())
            instance3966 = DarkOakDoorBlockType(3966.toShort(), 1, 1.toByte(), 0.toByte(), 0.toByte())
            instance3967 = DarkOakDoorBlockType(3967.toShort(), 2, 1.toByte(), 0.toByte(), 0.toByte())
            instance3968 = DarkOakDoorBlockType(3968.toShort(), 3, 1.toByte(), 0.toByte(), 0.toByte())
            instance3969 = DarkOakDoorBlockType(3969.toShort(), 0, 1.toByte(), 1.toByte(), 0.toByte())
            instance3970 = DarkOakDoorBlockType(3970.toShort(), 1, 1.toByte(), 1.toByte(), 0.toByte())
            instance3971 = DarkOakDoorBlockType(3971.toShort(), 2, 1.toByte(), 1.toByte(), 0.toByte())
            instance3972 = DarkOakDoorBlockType(3972.toShort(), 3, 1.toByte(), 1.toByte(), 0.toByte())
            instance3973 = DarkOakDoorBlockType(3973.toShort(), 0, 1.toByte(), 0.toByte(), 1.toByte())
            instance3974 = DarkOakDoorBlockType(3974.toShort(), 1, 1.toByte(), 0.toByte(), 1.toByte())
            instance3975 = DarkOakDoorBlockType(3975.toShort(), 2, 1.toByte(), 0.toByte(), 1.toByte())
            instance3976 = DarkOakDoorBlockType(3976.toShort(), 3, 1.toByte(), 0.toByte(), 1.toByte())
            instance3977 = DarkOakDoorBlockType(3977.toShort(), 0, 1.toByte(), 1.toByte(), 1.toByte())
            instance3978 = DarkOakDoorBlockType(3978.toShort(), 1, 1.toByte(), 1.toByte(), 1.toByte())
            instance3979 = DarkOakDoorBlockType(3979.toShort(), 2, 1.toByte(), 1.toByte(), 1.toByte())
            instance3980 = DarkOakDoorBlockType(3980.toShort(), 3, 1.toByte(), 1.toByte(), 1.toByte())
        }
    }
}
