// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DarkOakButtonBlockType private constructor(
    public override val runtimeID: Short,
    public val buttonPressedBit: Byte,
    public val facingDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        buttonPressedBit: Byte = this.buttonPressedBit,
        facingDirection: Int =
            this.facingDirection
    ): DarkOakButtonBlockType {
        val e = DarkOakButtonBlockType(0.toShort(), buttonPressedBit, facingDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DarkOakButtonBlockType): Boolean {
        var ret = true
        ret = ret && (this.buttonPressedBit == other.buttonPressedBit)
        ret = ret && (this.facingDirection == other.facingDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:dark_oak_button"

        public override val itemID: ItemID = ItemID(-142)

        private lateinit var instance3937: DarkOakButtonBlockType

        private lateinit var instance3938: DarkOakButtonBlockType

        private lateinit var instance3939: DarkOakButtonBlockType

        private lateinit var instance3940: DarkOakButtonBlockType

        private lateinit var instance3941: DarkOakButtonBlockType

        private lateinit var instance3942: DarkOakButtonBlockType

        private lateinit var instance3943: DarkOakButtonBlockType

        private lateinit var instance3944: DarkOakButtonBlockType

        private lateinit var instance3945: DarkOakButtonBlockType

        private lateinit var instance3946: DarkOakButtonBlockType

        private lateinit var instance3947: DarkOakButtonBlockType

        private lateinit var instance3948: DarkOakButtonBlockType

        init {
            init0()
        }

        public override val primary: DarkOakButtonBlockType = instance3937

        public override val allInstances: List<DarkOakButtonBlockType> =
            listOf(instance3937, instance3938, instance3939, instance3940, instance3941, instance3942, instance3943, instance3944, instance3945, instance3946, instance3947, instance3948)

        public fun init0() {
            instance3937 = DarkOakButtonBlockType(3937.toShort(), 0.toByte(), 0)
            instance3938 = DarkOakButtonBlockType(3938.toShort(), 0.toByte(), 1)
            instance3939 = DarkOakButtonBlockType(3939.toShort(), 0.toByte(), 2)
            instance3940 = DarkOakButtonBlockType(3940.toShort(), 0.toByte(), 3)
            instance3941 = DarkOakButtonBlockType(3941.toShort(), 0.toByte(), 4)
            instance3942 = DarkOakButtonBlockType(3942.toShort(), 0.toByte(), 5)
            instance3943 = DarkOakButtonBlockType(3943.toShort(), 1.toByte(), 0)
            instance3944 = DarkOakButtonBlockType(3944.toShort(), 1.toByte(), 1)
            instance3945 = DarkOakButtonBlockType(3945.toShort(), 1.toByte(), 2)
            instance3946 = DarkOakButtonBlockType(3946.toShort(), 1.toByte(), 3)
            instance3947 = DarkOakButtonBlockType(3947.toShort(), 1.toByte(), 4)
            instance3948 = DarkOakButtonBlockType(3948.toShort(), 1.toByte(), 5)
        }
    }
}
