// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DeepslateIronOreBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): DeepslateIronOreBlockType {
        val e = DeepslateIronOreBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DeepslateIronOreBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:deepslate_iron_ore"

        public override val itemID: ItemID = ItemID(-401)

        private lateinit var instance4283: DeepslateIronOreBlockType

        init {
            init0()
        }

        public override val primary: DeepslateIronOreBlockType = instance4283

        public override val allInstances: List<DeepslateIronOreBlockType> = listOf(instance4283)

        public fun init0() {
            instance4283 = DeepslateIronOreBlockType(4283.toShort())
        }
    }
}
