// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DeepslateRedstoneOreBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): DeepslateRedstoneOreBlockType {
        val e = DeepslateRedstoneOreBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DeepslateRedstoneOreBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:deepslate_redstone_ore"

        public override val itemID: ItemID = ItemID(-403)

        private lateinit var instance4285: DeepslateRedstoneOreBlockType

        init {
            init0()
        }

        public override val primary: DeepslateRedstoneOreBlockType = instance4285

        public override val allInstances: List<DeepslateRedstoneOreBlockType> = listOf(instance4285)

        public fun init0() {
            instance4285 = DeepslateRedstoneOreBlockType(4285.toShort())
        }
    }
}
