// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DetectorRailBlockType private constructor(
    public override val runtimeID: Short,
    public val railDataBit: Byte,
    public val railDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(railDataBit: Byte = this.railDataBit, railDirection: Int = this.railDirection):
        DetectorRailBlockType {
        val e = DetectorRailBlockType(0.toShort(), railDataBit, railDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DetectorRailBlockType): Boolean {
        var ret = true
        ret = ret && (this.railDataBit == other.railDataBit)
        ret = ret && (this.railDirection == other.railDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:detector_rail"

        public override val itemID: ItemID = ItemID(28)

        private lateinit var instance4462: DetectorRailBlockType

        private lateinit var instance4463: DetectorRailBlockType

        private lateinit var instance4464: DetectorRailBlockType

        private lateinit var instance4465: DetectorRailBlockType

        private lateinit var instance4466: DetectorRailBlockType

        private lateinit var instance4467: DetectorRailBlockType

        private lateinit var instance4468: DetectorRailBlockType

        private lateinit var instance4469: DetectorRailBlockType

        private lateinit var instance4470: DetectorRailBlockType

        private lateinit var instance4471: DetectorRailBlockType

        private lateinit var instance4472: DetectorRailBlockType

        private lateinit var instance4473: DetectorRailBlockType

        init {
            init0()
        }

        public override val primary: DetectorRailBlockType = instance4462

        public override val allInstances: List<DetectorRailBlockType> =
            listOf(instance4462, instance4463, instance4464, instance4465, instance4466, instance4467, instance4468, instance4469, instance4470, instance4471, instance4472, instance4473)

        public fun init0() {
            instance4462 = DetectorRailBlockType(4462.toShort(), 0.toByte(), 0)
            instance4463 = DetectorRailBlockType(4463.toShort(), 0.toByte(), 1)
            instance4464 = DetectorRailBlockType(4464.toShort(), 0.toByte(), 2)
            instance4465 = DetectorRailBlockType(4465.toShort(), 0.toByte(), 3)
            instance4466 = DetectorRailBlockType(4466.toShort(), 0.toByte(), 4)
            instance4467 = DetectorRailBlockType(4467.toShort(), 0.toByte(), 5)
            instance4468 = DetectorRailBlockType(4468.toShort(), 1.toByte(), 0)
            instance4469 = DetectorRailBlockType(4469.toShort(), 1.toByte(), 1)
            instance4470 = DetectorRailBlockType(4470.toShort(), 1.toByte(), 2)
            instance4471 = DetectorRailBlockType(4471.toShort(), 1.toByte(), 3)
            instance4472 = DetectorRailBlockType(4472.toShort(), 1.toByte(), 4)
            instance4473 = DetectorRailBlockType(4473.toShort(), 1.toByte(), 5)
        }
    }
}
