// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DoubleStoneSlabBlockType private constructor(
    public override val runtimeID: Short,
    public val stoneSlabType: String,
    public val topSlotBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(stoneSlabType: String = this.stoneSlabType, topSlotBit: Byte = this.topSlotBit):
        DoubleStoneSlabBlockType {
        val e = DoubleStoneSlabBlockType(0.toShort(), stoneSlabType, topSlotBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DoubleStoneSlabBlockType): Boolean {
        var ret = true
        ret = ret && (this.stoneSlabType == other.stoneSlabType)
        ret = ret && (this.topSlotBit == other.topSlotBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:double_stone_slab"

        public override val itemID: ItemID = ItemID(44)

        private lateinit var instance4513: DoubleStoneSlabBlockType

        private lateinit var instance4514: DoubleStoneSlabBlockType

        private lateinit var instance4515: DoubleStoneSlabBlockType

        private lateinit var instance4516: DoubleStoneSlabBlockType

        private lateinit var instance4517: DoubleStoneSlabBlockType

        private lateinit var instance4518: DoubleStoneSlabBlockType

        private lateinit var instance4519: DoubleStoneSlabBlockType

        private lateinit var instance4520: DoubleStoneSlabBlockType

        private lateinit var instance4521: DoubleStoneSlabBlockType

        private lateinit var instance4522: DoubleStoneSlabBlockType

        private lateinit var instance4523: DoubleStoneSlabBlockType

        private lateinit var instance4524: DoubleStoneSlabBlockType

        private lateinit var instance4525: DoubleStoneSlabBlockType

        private lateinit var instance4526: DoubleStoneSlabBlockType

        private lateinit var instance4527: DoubleStoneSlabBlockType

        private lateinit var instance4528: DoubleStoneSlabBlockType

        init {
            init0()
        }

        public override val primary: DoubleStoneSlabBlockType = instance4513

        public override val allInstances: List<DoubleStoneSlabBlockType> =
            listOf(instance4513, instance4514, instance4515, instance4516, instance4517, instance4518, instance4519, instance4520, instance4521, instance4522, instance4523, instance4524, instance4525, instance4526, instance4527, instance4528)

        public fun init0() {
            instance4513 = DoubleStoneSlabBlockType(4513.toShort(), "smooth_stone", 0.toByte())
            instance4514 = DoubleStoneSlabBlockType(4514.toShort(), "sandstone", 0.toByte())
            instance4515 = DoubleStoneSlabBlockType(4515.toShort(), "wood", 0.toByte())
            instance4516 = DoubleStoneSlabBlockType(4516.toShort(), "cobblestone", 0.toByte())
            instance4517 = DoubleStoneSlabBlockType(4517.toShort(), "brick", 0.toByte())
            instance4518 = DoubleStoneSlabBlockType(4518.toShort(), "stone_brick", 0.toByte())
            instance4519 = DoubleStoneSlabBlockType(4519.toShort(), "quartz", 0.toByte())
            instance4520 = DoubleStoneSlabBlockType(4520.toShort(), "nether_brick", 0.toByte())
            instance4521 = DoubleStoneSlabBlockType(4521.toShort(), "smooth_stone", 1.toByte())
            instance4522 = DoubleStoneSlabBlockType(4522.toShort(), "sandstone", 1.toByte())
            instance4523 = DoubleStoneSlabBlockType(4523.toShort(), "wood", 1.toByte())
            instance4524 = DoubleStoneSlabBlockType(4524.toShort(), "cobblestone", 1.toByte())
            instance4525 = DoubleStoneSlabBlockType(4525.toShort(), "brick", 1.toByte())
            instance4526 = DoubleStoneSlabBlockType(4526.toShort(), "stone_brick", 1.toByte())
            instance4527 = DoubleStoneSlabBlockType(4527.toShort(), "quartz", 1.toByte())
            instance4528 = DoubleStoneSlabBlockType(4528.toShort(), "nether_brick", 1.toByte())
        }
    }
}
