// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DoubleStoneSlab2BlockType private constructor(
    public override val runtimeID: Short,
    public val stoneSlabType2: String,
    public val topSlotBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(stoneSlabType2: String = this.stoneSlabType2, topSlotBit: Byte = this.topSlotBit):
        DoubleStoneSlab2BlockType {
        val e = DoubleStoneSlab2BlockType(0.toShort(), stoneSlabType2, topSlotBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DoubleStoneSlab2BlockType): Boolean {
        var ret = true
        ret = ret && (this.stoneSlabType2 == other.stoneSlabType2)
        ret = ret && (this.topSlotBit == other.topSlotBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:double_stone_slab2"

        public override val itemID: ItemID = ItemID(182)

        private lateinit var instance4529: DoubleStoneSlab2BlockType

        private lateinit var instance4530: DoubleStoneSlab2BlockType

        private lateinit var instance4531: DoubleStoneSlab2BlockType

        private lateinit var instance4532: DoubleStoneSlab2BlockType

        private lateinit var instance4533: DoubleStoneSlab2BlockType

        private lateinit var instance4534: DoubleStoneSlab2BlockType

        private lateinit var instance4535: DoubleStoneSlab2BlockType

        private lateinit var instance4536: DoubleStoneSlab2BlockType

        private lateinit var instance4537: DoubleStoneSlab2BlockType

        private lateinit var instance4538: DoubleStoneSlab2BlockType

        private lateinit var instance4539: DoubleStoneSlab2BlockType

        private lateinit var instance4540: DoubleStoneSlab2BlockType

        private lateinit var instance4541: DoubleStoneSlab2BlockType

        private lateinit var instance4542: DoubleStoneSlab2BlockType

        private lateinit var instance4543: DoubleStoneSlab2BlockType

        private lateinit var instance4544: DoubleStoneSlab2BlockType

        init {
            init0()
        }

        public override val primary: DoubleStoneSlab2BlockType = instance4529

        public override val allInstances: List<DoubleStoneSlab2BlockType> =
            listOf(instance4529, instance4530, instance4531, instance4532, instance4533, instance4534, instance4535, instance4536, instance4537, instance4538, instance4539, instance4540, instance4541, instance4542, instance4543, instance4544)

        public fun init0() {
            instance4529 = DoubleStoneSlab2BlockType(4529.toShort(), "red_sandstone", 0.toByte())
            instance4530 = DoubleStoneSlab2BlockType(4530.toShort(), "purpur", 0.toByte())
            instance4531 = DoubleStoneSlab2BlockType(4531.toShort(), "prismarine_rough", 0.toByte())
            instance4532 = DoubleStoneSlab2BlockType(4532.toShort(), "prismarine_dark", 0.toByte())
            instance4533 = DoubleStoneSlab2BlockType(4533.toShort(), "prismarine_brick", 0.toByte())
            instance4534 = DoubleStoneSlab2BlockType(4534.toShort(), "mossy_cobblestone", 0.toByte())
            instance4535 = DoubleStoneSlab2BlockType(4535.toShort(), "smooth_sandstone", 0.toByte())
            instance4536 = DoubleStoneSlab2BlockType(4536.toShort(), "red_nether_brick", 0.toByte())
            instance4537 = DoubleStoneSlab2BlockType(4537.toShort(), "red_sandstone", 1.toByte())
            instance4538 = DoubleStoneSlab2BlockType(4538.toShort(), "purpur", 1.toByte())
            instance4539 = DoubleStoneSlab2BlockType(4539.toShort(), "prismarine_rough", 1.toByte())
            instance4540 = DoubleStoneSlab2BlockType(4540.toShort(), "prismarine_dark", 1.toByte())
            instance4541 = DoubleStoneSlab2BlockType(4541.toShort(), "prismarine_brick", 1.toByte())
            instance4542 = DoubleStoneSlab2BlockType(4542.toShort(), "mossy_cobblestone", 1.toByte())
            instance4543 = DoubleStoneSlab2BlockType(4543.toShort(), "smooth_sandstone", 1.toByte())
            instance4544 = DoubleStoneSlab2BlockType(4544.toShort(), "red_nether_brick", 1.toByte())
        }
    }
}
