// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DriedKelpBlockBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): DriedKelpBlockBlockType {
        val e = DriedKelpBlockBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DriedKelpBlockBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:dried_kelp_block"

        public override val itemID: ItemID = ItemID(-139)

        private lateinit var instance4584: DriedKelpBlockBlockType

        init {
            init0()
        }

        public override val primary: DriedKelpBlockBlockType = instance4584

        public override val allInstances: List<DriedKelpBlockBlockType> = listOf(instance4584)

        public fun init0() {
            instance4584 = DriedKelpBlockBlockType(4584.toShort())
        }
    }
}
