// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class DropperBlockType private constructor(
    public override val runtimeID: Short,
    public val facingDirection: Int,
    public val triggeredBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        facingDirection: Int = this.facingDirection,
        triggeredBit: Byte =
            this.triggeredBit
    ): DropperBlockType {
        val e = DropperBlockType(0.toShort(), facingDirection, triggeredBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: DropperBlockType): Boolean {
        var ret = true
        ret = ret && (this.facingDirection == other.facingDirection)
        ret = ret && (this.triggeredBit == other.triggeredBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:dropper"

        public override val itemID: ItemID = ItemID(125)

        private lateinit var instance4586: DropperBlockType

        private lateinit var instance4587: DropperBlockType

        private lateinit var instance4588: DropperBlockType

        private lateinit var instance4589: DropperBlockType

        private lateinit var instance4590: DropperBlockType

        private lateinit var instance4591: DropperBlockType

        private lateinit var instance4592: DropperBlockType

        private lateinit var instance4593: DropperBlockType

        private lateinit var instance4594: DropperBlockType

        private lateinit var instance4595: DropperBlockType

        private lateinit var instance4596: DropperBlockType

        private lateinit var instance4597: DropperBlockType

        init {
            init0()
        }

        public override val primary: DropperBlockType = instance4586

        public override val allInstances: List<DropperBlockType> =
            listOf(instance4586, instance4587, instance4588, instance4589, instance4590, instance4591, instance4592, instance4593, instance4594, instance4595, instance4596, instance4597)

        public fun init0() {
            instance4586 = DropperBlockType(4586.toShort(), 0, 0.toByte())
            instance4587 = DropperBlockType(4587.toShort(), 1, 0.toByte())
            instance4588 = DropperBlockType(4588.toShort(), 2, 0.toByte())
            instance4589 = DropperBlockType(4589.toShort(), 3, 0.toByte())
            instance4590 = DropperBlockType(4590.toShort(), 4, 0.toByte())
            instance4591 = DropperBlockType(4591.toShort(), 5, 0.toByte())
            instance4592 = DropperBlockType(4592.toShort(), 0, 1.toByte())
            instance4593 = DropperBlockType(4593.toShort(), 1, 1.toByte())
            instance4594 = DropperBlockType(4594.toShort(), 2, 1.toByte())
            instance4595 = DropperBlockType(4595.toShort(), 3, 1.toByte())
            instance4596 = DropperBlockType(4596.toShort(), 4, 1.toByte())
            instance4597 = DropperBlockType(4597.toShort(), 5, 1.toByte())
        }
    }
}
