// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class Element72BlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): Element72BlockType {
        val e = Element72BlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: Element72BlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:element_72"

        public override val itemID: ItemID = ItemID(-83)

        private lateinit var instance4687: Element72BlockType

        init {
            init0()
        }

        public override val primary: Element72BlockType = instance4687

        public override val allInstances: List<Element72BlockType> = listOf(instance4687)

        public fun init0() {
            instance4687 = Element72BlockType(4687.toShort())
        }
    }
}
