// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class Element41BlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): Element41BlockType {
        val e = Element41BlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: Element41BlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:element_41"

        public override val itemID: ItemID = ItemID(-52)

        private lateinit var instance4653: Element41BlockType

        init {
            init0()
        }

        public override val primary: Element41BlockType = instance4653

        public override val allInstances: List<Element41BlockType> = listOf(instance4653)

        public fun init0() {
            instance4653 = Element41BlockType(4653.toShort())
        }
    }
}
