// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class Element112BlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): Element112BlockType {
        val e = Element112BlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: Element112BlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:element_112"

        public override val itemID: ItemID = ItemID(-123)

        private lateinit var instance4614: Element112BlockType

        init {
            init0()
        }

        public override val primary: Element112BlockType = instance4614

        public override val allInstances: List<Element112BlockType> = listOf(instance4614)

        public fun init0() {
            instance4614 = Element112BlockType(4614.toShort())
        }
    }
}
