// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class Element57BlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): Element57BlockType {
        val e = Element57BlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: Element57BlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:element_57"

        public override val itemID: ItemID = ItemID(-68)

        private lateinit var instance4670: Element57BlockType

        init {
            init0()
        }

        public override val primary: Element57BlockType = instance4670

        public override val allInstances: List<Element57BlockType> = listOf(instance4670)

        public fun init0() {
            instance4670 = Element57BlockType(4670.toShort())
        }
    }
}
