// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class Element88BlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): Element88BlockType {
        val e = Element88BlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: Element88BlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:element_88"

        public override val itemID: ItemID = ItemID(-99)

        private lateinit var instance4704: Element88BlockType

        init {
            init0()
        }

        public override val primary: Element88BlockType = instance4704

        public override val allInstances: List<Element88BlockType> = listOf(instance4704)

        public fun init0() {
            instance4704 = Element88BlockType(4704.toShort())
        }
    }
}
