// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class Element11BlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): Element11BlockType {
        val e = Element11BlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: Element11BlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:element_11"

        public override val itemID: ItemID = ItemID(-22)

        private lateinit var instance4611: Element11BlockType

        init {
            init0()
        }

        public override val primary: Element11BlockType = instance4611

        public override val allInstances: List<Element11BlockType> = listOf(instance4611)

        public fun init0() {
            instance4611 = Element11BlockType(4611.toShort())
        }
    }
}
