// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class Element46BlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): Element46BlockType {
        val e = Element46BlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: Element46BlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:element_46"

        public override val itemID: ItemID = ItemID(-57)

        private lateinit var instance4658: Element46BlockType

        init {
            init0()
        }

        public override val primary: Element46BlockType = instance4658

        public override val allInstances: List<Element46BlockType> = listOf(instance4658)

        public fun init0() {
            instance4658 = Element46BlockType(4658.toShort())
        }
    }
}
