// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class Element85BlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): Element85BlockType {
        val e = Element85BlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: Element85BlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:element_85"

        public override val itemID: ItemID = ItemID(-96)

        private lateinit var instance4701: Element85BlockType

        init {
            init0()
        }

        public override val primary: Element85BlockType = instance4701

        public override val allInstances: List<Element85BlockType> = listOf(instance4701)

        public fun init0() {
            instance4701 = Element85BlockType(4701.toShort())
        }
    }
}
