// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class FloweringAzaleaBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): FloweringAzaleaBlockType {
        val e = FloweringAzaleaBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: FloweringAzaleaBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:flowering_azalea"

        public override val itemID: ItemID = ItemID(-338)

        private lateinit var instance4815: FloweringAzaleaBlockType

        init {
            init0()
        }

        public override val primary: FloweringAzaleaBlockType = instance4815

        public override val allInstances: List<FloweringAzaleaBlockType> = listOf(instance4815)

        public fun init0() {
            instance4815 = FloweringAzaleaBlockType(4815.toShort())
        }
    }
}
