// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class GlassPaneBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): GlassPaneBlockType {
        val e = GlassPaneBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: GlassPaneBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:glass_pane"

        public override val itemID: ItemID = ItemID(102)

        private lateinit var instance4885: GlassPaneBlockType

        init {
            init0()
        }

        public override val primary: GlassPaneBlockType = instance4885

        public override val allInstances: List<GlassPaneBlockType> = listOf(instance4885)

        public fun init0() {
            instance4885 = GlassPaneBlockType(4885.toShort())
        }
    }
}
