// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class GlowLichenBlockType private constructor(
    public override val runtimeID: Short,
    public val multiFaceDirectionBits: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(multiFaceDirectionBits: Int = this.multiFaceDirectionBits): GlowLichenBlockType {
        val e = GlowLichenBlockType(0.toShort(), multiFaceDirectionBits)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: GlowLichenBlockType): Boolean {
        var ret = true
        ret = ret && (this.multiFaceDirectionBits == other.multiFaceDirectionBits)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:glow_lichen"

        public override val itemID: ItemID = ItemID(-411)

        private lateinit var instance4910: GlowLichenBlockType

        private lateinit var instance4911: GlowLichenBlockType

        private lateinit var instance4912: GlowLichenBlockType

        private lateinit var instance4913: GlowLichenBlockType

        private lateinit var instance4914: GlowLichenBlockType

        private lateinit var instance4915: GlowLichenBlockType

        private lateinit var instance4916: GlowLichenBlockType

        private lateinit var instance4917: GlowLichenBlockType

        private lateinit var instance4918: GlowLichenBlockType

        private lateinit var instance4919: GlowLichenBlockType

        private lateinit var instance4920: GlowLichenBlockType

        private lateinit var instance4921: GlowLichenBlockType

        private lateinit var instance4922: GlowLichenBlockType

        private lateinit var instance4923: GlowLichenBlockType

        private lateinit var instance4924: GlowLichenBlockType

        private lateinit var instance4925: GlowLichenBlockType

        private lateinit var instance4926: GlowLichenBlockType

        private lateinit var instance4927: GlowLichenBlockType

        private lateinit var instance4928: GlowLichenBlockType

        private lateinit var instance4929: GlowLichenBlockType

        private lateinit var instance4930: GlowLichenBlockType

        private lateinit var instance4931: GlowLichenBlockType

        private lateinit var instance4932: GlowLichenBlockType

        private lateinit var instance4933: GlowLichenBlockType

        private lateinit var instance4934: GlowLichenBlockType

        private lateinit var instance4935: GlowLichenBlockType

        private lateinit var instance4936: GlowLichenBlockType

        private lateinit var instance4937: GlowLichenBlockType

        private lateinit var instance4938: GlowLichenBlockType

        private lateinit var instance4939: GlowLichenBlockType

        private lateinit var instance4940: GlowLichenBlockType

        private lateinit var instance4941: GlowLichenBlockType

        private lateinit var instance4942: GlowLichenBlockType

        private lateinit var instance4943: GlowLichenBlockType

        private lateinit var instance4944: GlowLichenBlockType

        private lateinit var instance4945: GlowLichenBlockType

        private lateinit var instance4946: GlowLichenBlockType

        private lateinit var instance4947: GlowLichenBlockType

        private lateinit var instance4948: GlowLichenBlockType

        private lateinit var instance4949: GlowLichenBlockType

        private lateinit var instance4950: GlowLichenBlockType

        private lateinit var instance4951: GlowLichenBlockType

        private lateinit var instance4952: GlowLichenBlockType

        private lateinit var instance4953: GlowLichenBlockType

        private lateinit var instance4954: GlowLichenBlockType

        private lateinit var instance4955: GlowLichenBlockType

        private lateinit var instance4956: GlowLichenBlockType

        private lateinit var instance4957: GlowLichenBlockType

        private lateinit var instance4958: GlowLichenBlockType

        private lateinit var instance4959: GlowLichenBlockType

        private lateinit var instance4960: GlowLichenBlockType

        private lateinit var instance4961: GlowLichenBlockType

        private lateinit var instance4962: GlowLichenBlockType

        private lateinit var instance4963: GlowLichenBlockType

        private lateinit var instance4964: GlowLichenBlockType

        private lateinit var instance4965: GlowLichenBlockType

        private lateinit var instance4966: GlowLichenBlockType

        private lateinit var instance4967: GlowLichenBlockType

        private lateinit var instance4968: GlowLichenBlockType

        private lateinit var instance4969: GlowLichenBlockType

        private lateinit var instance4970: GlowLichenBlockType

        private lateinit var instance4971: GlowLichenBlockType

        private lateinit var instance4972: GlowLichenBlockType

        private lateinit var instance4973: GlowLichenBlockType

        init {
            init0()
        }

        public override val primary: GlowLichenBlockType = instance4910

        public override val allInstances: List<GlowLichenBlockType> =
            listOf(instance4910, instance4911, instance4912, instance4913, instance4914, instance4915, instance4916, instance4917, instance4918, instance4919, instance4920, instance4921, instance4922, instance4923, instance4924, instance4925, instance4926, instance4927, instance4928, instance4929, instance4930, instance4931, instance4932, instance4933, instance4934, instance4935, instance4936, instance4937, instance4938, instance4939, instance4940, instance4941, instance4942, instance4943, instance4944, instance4945, instance4946, instance4947, instance4948, instance4949, instance4950, instance4951, instance4952, instance4953, instance4954, instance4955, instance4956, instance4957, instance4958, instance4959, instance4960, instance4961, instance4962, instance4963, instance4964, instance4965, instance4966, instance4967, instance4968, instance4969, instance4970, instance4971, instance4972, instance4973)

        public fun init0() {
            instance4910 = GlowLichenBlockType(4910.toShort(), 0)
            instance4911 = GlowLichenBlockType(4911.toShort(), 1)
            instance4912 = GlowLichenBlockType(4912.toShort(), 2)
            instance4913 = GlowLichenBlockType(4913.toShort(), 3)
            instance4914 = GlowLichenBlockType(4914.toShort(), 4)
            instance4915 = GlowLichenBlockType(4915.toShort(), 5)
            instance4916 = GlowLichenBlockType(4916.toShort(), 6)
            instance4917 = GlowLichenBlockType(4917.toShort(), 7)
            instance4918 = GlowLichenBlockType(4918.toShort(), 8)
            instance4919 = GlowLichenBlockType(4919.toShort(), 9)
            instance4920 = GlowLichenBlockType(4920.toShort(), 10)
            instance4921 = GlowLichenBlockType(4921.toShort(), 11)
            instance4922 = GlowLichenBlockType(4922.toShort(), 12)
            instance4923 = GlowLichenBlockType(4923.toShort(), 13)
            instance4924 = GlowLichenBlockType(4924.toShort(), 14)
            instance4925 = GlowLichenBlockType(4925.toShort(), 15)
            instance4926 = GlowLichenBlockType(4926.toShort(), 16)
            instance4927 = GlowLichenBlockType(4927.toShort(), 17)
            instance4928 = GlowLichenBlockType(4928.toShort(), 18)
            instance4929 = GlowLichenBlockType(4929.toShort(), 19)
            instance4930 = GlowLichenBlockType(4930.toShort(), 20)
            instance4931 = GlowLichenBlockType(4931.toShort(), 21)
            instance4932 = GlowLichenBlockType(4932.toShort(), 22)
            instance4933 = GlowLichenBlockType(4933.toShort(), 23)
            instance4934 = GlowLichenBlockType(4934.toShort(), 24)
            instance4935 = GlowLichenBlockType(4935.toShort(), 25)
            instance4936 = GlowLichenBlockType(4936.toShort(), 26)
            instance4937 = GlowLichenBlockType(4937.toShort(), 27)
            instance4938 = GlowLichenBlockType(4938.toShort(), 28)
            instance4939 = GlowLichenBlockType(4939.toShort(), 29)
            instance4940 = GlowLichenBlockType(4940.toShort(), 30)
            instance4941 = GlowLichenBlockType(4941.toShort(), 31)
            instance4942 = GlowLichenBlockType(4942.toShort(), 32)
            instance4943 = GlowLichenBlockType(4943.toShort(), 33)
            instance4944 = GlowLichenBlockType(4944.toShort(), 34)
            instance4945 = GlowLichenBlockType(4945.toShort(), 35)
            instance4946 = GlowLichenBlockType(4946.toShort(), 36)
            instance4947 = GlowLichenBlockType(4947.toShort(), 37)
            instance4948 = GlowLichenBlockType(4948.toShort(), 38)
            instance4949 = GlowLichenBlockType(4949.toShort(), 39)
            instance4950 = GlowLichenBlockType(4950.toShort(), 40)
            instance4951 = GlowLichenBlockType(4951.toShort(), 41)
            instance4952 = GlowLichenBlockType(4952.toShort(), 42)
            instance4953 = GlowLichenBlockType(4953.toShort(), 43)
            instance4954 = GlowLichenBlockType(4954.toShort(), 44)
            instance4955 = GlowLichenBlockType(4955.toShort(), 45)
            instance4956 = GlowLichenBlockType(4956.toShort(), 46)
            instance4957 = GlowLichenBlockType(4957.toShort(), 47)
            instance4958 = GlowLichenBlockType(4958.toShort(), 48)
            instance4959 = GlowLichenBlockType(4959.toShort(), 49)
            instance4960 = GlowLichenBlockType(4960.toShort(), 50)
            instance4961 = GlowLichenBlockType(4961.toShort(), 51)
            instance4962 = GlowLichenBlockType(4962.toShort(), 52)
            instance4963 = GlowLichenBlockType(4963.toShort(), 53)
            instance4964 = GlowLichenBlockType(4964.toShort(), 54)
            instance4965 = GlowLichenBlockType(4965.toShort(), 55)
            instance4966 = GlowLichenBlockType(4966.toShort(), 56)
            instance4967 = GlowLichenBlockType(4967.toShort(), 57)
            instance4968 = GlowLichenBlockType(4968.toShort(), 58)
            instance4969 = GlowLichenBlockType(4969.toShort(), 59)
            instance4970 = GlowLichenBlockType(4970.toShort(), 60)
            instance4971 = GlowLichenBlockType(4971.toShort(), 61)
            instance4972 = GlowLichenBlockType(4972.toShort(), 62)
            instance4973 = GlowLichenBlockType(4973.toShort(), 63)
        }
    }
}
