// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class GravelBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): GravelBlockType {
        val e = GravelBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: GravelBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:gravel"

        public override val itemID: ItemID = ItemID(13)

        private lateinit var instance5000: GravelBlockType

        init {
            init0()
        }

        public override val primary: GravelBlockType = instance5000

        public override val allInstances: List<GravelBlockType> = listOf(instance5000)

        public fun init0() {
            instance5000 = GravelBlockType(5000.toShort())
        }
    }
}
