// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class IronDoorBlockType private constructor(
    public override val runtimeID: Short,
    public val direction: Int,
    public val doorHingeBit: Byte,
    public val openBit: Byte,
    public val upperBlockBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        direction: Int = this.direction,
        doorHingeBit: Byte = this.doorHingeBit,
        openBit: Byte = this.openBit,
        upperBlockBit: Byte = this.upperBlockBit
    ): IronDoorBlockType {
        val e = IronDoorBlockType(0.toShort(), direction, doorHingeBit, openBit, upperBlockBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: IronDoorBlockType): Boolean {
        var ret = true
        ret = ret && (this.direction == other.direction)
        ret = ret && (this.doorHingeBit == other.doorHingeBit)
        ret = ret && (this.openBit == other.openBit)
        ret = ret && (this.upperBlockBit == other.upperBlockBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:iron_door"

        public override val itemID: ItemID = ItemID(71)

        private lateinit var instance5136: IronDoorBlockType

        private lateinit var instance5137: IronDoorBlockType

        private lateinit var instance5138: IronDoorBlockType

        private lateinit var instance5139: IronDoorBlockType

        private lateinit var instance5140: IronDoorBlockType

        private lateinit var instance5141: IronDoorBlockType

        private lateinit var instance5142: IronDoorBlockType

        private lateinit var instance5143: IronDoorBlockType

        private lateinit var instance5144: IronDoorBlockType

        private lateinit var instance5145: IronDoorBlockType

        private lateinit var instance5146: IronDoorBlockType

        private lateinit var instance5147: IronDoorBlockType

        private lateinit var instance5148: IronDoorBlockType

        private lateinit var instance5149: IronDoorBlockType

        private lateinit var instance5150: IronDoorBlockType

        private lateinit var instance5151: IronDoorBlockType

        private lateinit var instance5152: IronDoorBlockType

        private lateinit var instance5153: IronDoorBlockType

        private lateinit var instance5154: IronDoorBlockType

        private lateinit var instance5155: IronDoorBlockType

        private lateinit var instance5156: IronDoorBlockType

        private lateinit var instance5157: IronDoorBlockType

        private lateinit var instance5158: IronDoorBlockType

        private lateinit var instance5159: IronDoorBlockType

        private lateinit var instance5160: IronDoorBlockType

        private lateinit var instance5161: IronDoorBlockType

        private lateinit var instance5162: IronDoorBlockType

        private lateinit var instance5163: IronDoorBlockType

        private lateinit var instance5164: IronDoorBlockType

        private lateinit var instance5165: IronDoorBlockType

        private lateinit var instance5166: IronDoorBlockType

        private lateinit var instance5167: IronDoorBlockType

        init {
            init0()
        }

        public override val primary: IronDoorBlockType = instance5136

        public override val allInstances: List<IronDoorBlockType> =
            listOf(instance5136, instance5137, instance5138, instance5139, instance5140, instance5141, instance5142, instance5143, instance5144, instance5145, instance5146, instance5147, instance5148, instance5149, instance5150, instance5151, instance5152, instance5153, instance5154, instance5155, instance5156, instance5157, instance5158, instance5159, instance5160, instance5161, instance5162, instance5163, instance5164, instance5165, instance5166, instance5167)

        public fun init0() {
            instance5136 = IronDoorBlockType(5136.toShort(), 0, 0.toByte(), 0.toByte(), 0.toByte())
            instance5137 = IronDoorBlockType(5137.toShort(), 1, 0.toByte(), 0.toByte(), 0.toByte())
            instance5138 = IronDoorBlockType(5138.toShort(), 2, 0.toByte(), 0.toByte(), 0.toByte())
            instance5139 = IronDoorBlockType(5139.toShort(), 3, 0.toByte(), 0.toByte(), 0.toByte())
            instance5140 = IronDoorBlockType(5140.toShort(), 0, 0.toByte(), 1.toByte(), 0.toByte())
            instance5141 = IronDoorBlockType(5141.toShort(), 1, 0.toByte(), 1.toByte(), 0.toByte())
            instance5142 = IronDoorBlockType(5142.toShort(), 2, 0.toByte(), 1.toByte(), 0.toByte())
            instance5143 = IronDoorBlockType(5143.toShort(), 3, 0.toByte(), 1.toByte(), 0.toByte())
            instance5144 = IronDoorBlockType(5144.toShort(), 0, 0.toByte(), 0.toByte(), 1.toByte())
            instance5145 = IronDoorBlockType(5145.toShort(), 1, 0.toByte(), 0.toByte(), 1.toByte())
            instance5146 = IronDoorBlockType(5146.toShort(), 2, 0.toByte(), 0.toByte(), 1.toByte())
            instance5147 = IronDoorBlockType(5147.toShort(), 3, 0.toByte(), 0.toByte(), 1.toByte())
            instance5148 = IronDoorBlockType(5148.toShort(), 0, 0.toByte(), 1.toByte(), 1.toByte())
            instance5149 = IronDoorBlockType(5149.toShort(), 1, 0.toByte(), 1.toByte(), 1.toByte())
            instance5150 = IronDoorBlockType(5150.toShort(), 2, 0.toByte(), 1.toByte(), 1.toByte())
            instance5151 = IronDoorBlockType(5151.toShort(), 3, 0.toByte(), 1.toByte(), 1.toByte())
            instance5152 = IronDoorBlockType(5152.toShort(), 0, 1.toByte(), 0.toByte(), 0.toByte())
            instance5153 = IronDoorBlockType(5153.toShort(), 1, 1.toByte(), 0.toByte(), 0.toByte())
            instance5154 = IronDoorBlockType(5154.toShort(), 2, 1.toByte(), 0.toByte(), 0.toByte())
            instance5155 = IronDoorBlockType(5155.toShort(), 3, 1.toByte(), 0.toByte(), 0.toByte())
            instance5156 = IronDoorBlockType(5156.toShort(), 0, 1.toByte(), 1.toByte(), 0.toByte())
            instance5157 = IronDoorBlockType(5157.toShort(), 1, 1.toByte(), 1.toByte(), 0.toByte())
            instance5158 = IronDoorBlockType(5158.toShort(), 2, 1.toByte(), 1.toByte(), 0.toByte())
            instance5159 = IronDoorBlockType(5159.toShort(), 3, 1.toByte(), 1.toByte(), 0.toByte())
            instance5160 = IronDoorBlockType(5160.toShort(), 0, 1.toByte(), 0.toByte(), 1.toByte())
            instance5161 = IronDoorBlockType(5161.toShort(), 1, 1.toByte(), 0.toByte(), 1.toByte())
            instance5162 = IronDoorBlockType(5162.toShort(), 2, 1.toByte(), 0.toByte(), 1.toByte())
            instance5163 = IronDoorBlockType(5163.toShort(), 3, 1.toByte(), 0.toByte(), 1.toByte())
            instance5164 = IronDoorBlockType(5164.toShort(), 0, 1.toByte(), 1.toByte(), 1.toByte())
            instance5165 = IronDoorBlockType(5165.toShort(), 1, 1.toByte(), 1.toByte(), 1.toByte())
            instance5166 = IronDoorBlockType(5166.toShort(), 2, 1.toByte(), 1.toByte(), 1.toByte())
            instance5167 = IronDoorBlockType(5167.toShort(), 3, 1.toByte(), 1.toByte(), 1.toByte())
        }
    }
}
