// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class JungleStairsBlockType private constructor(
    public override val runtimeID: Short,
    public val upsideDownBit: Byte,
    public val weirdoDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        upsideDownBit: Byte = this.upsideDownBit,
        weirdoDirection: Int =
            this.weirdoDirection
    ): JungleStairsBlockType {
        val e = JungleStairsBlockType(0.toShort(), upsideDownBit, weirdoDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: JungleStairsBlockType): Boolean {
        var ret = true
        ret = ret && (this.upsideDownBit == other.upsideDownBit)
        ret = ret && (this.weirdoDirection == other.weirdoDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:jungle_stairs"

        public override val itemID: ItemID = ItemID(136)

        private lateinit var instance5286: JungleStairsBlockType

        private lateinit var instance5287: JungleStairsBlockType

        private lateinit var instance5288: JungleStairsBlockType

        private lateinit var instance5289: JungleStairsBlockType

        private lateinit var instance5290: JungleStairsBlockType

        private lateinit var instance5291: JungleStairsBlockType

        private lateinit var instance5292: JungleStairsBlockType

        private lateinit var instance5293: JungleStairsBlockType

        init {
            init0()
        }

        public override val primary: JungleStairsBlockType = instance5286

        public override val allInstances: List<JungleStairsBlockType> =
            listOf(instance5286, instance5287, instance5288, instance5289, instance5290, instance5291, instance5292, instance5293)

        public fun init0() {
            instance5286 = JungleStairsBlockType(5286.toShort(), 0.toByte(), 0)
            instance5287 = JungleStairsBlockType(5287.toShort(), 0.toByte(), 1)
            instance5288 = JungleStairsBlockType(5288.toShort(), 0.toByte(), 2)
            instance5289 = JungleStairsBlockType(5289.toShort(), 0.toByte(), 3)
            instance5290 = JungleStairsBlockType(5290.toShort(), 1.toByte(), 0)
            instance5291 = JungleStairsBlockType(5291.toShort(), 1.toByte(), 1)
            instance5292 = JungleStairsBlockType(5292.toShort(), 1.toByte(), 2)
            instance5293 = JungleStairsBlockType(5293.toShort(), 1.toByte(), 3)
        }
    }
}
