// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class KelpBlockType private constructor(
    public override val runtimeID: Short,
    public val kelpAge: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(kelpAge: Int = this.kelpAge): KelpBlockType {
        val e = KelpBlockType(0.toShort(), kelpAge)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: KelpBlockType): Boolean {
        var ret = true
        ret = ret && (this.kelpAge == other.kelpAge)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:kelp"

        public override val itemID: ItemID = ItemID(-138)

        private lateinit var instance5332: KelpBlockType

        private lateinit var instance5333: KelpBlockType

        private lateinit var instance5334: KelpBlockType

        private lateinit var instance5335: KelpBlockType

        private lateinit var instance5336: KelpBlockType

        private lateinit var instance5337: KelpBlockType

        private lateinit var instance5338: KelpBlockType

        private lateinit var instance5339: KelpBlockType

        private lateinit var instance5340: KelpBlockType

        private lateinit var instance5341: KelpBlockType

        private lateinit var instance5342: KelpBlockType

        private lateinit var instance5343: KelpBlockType

        private lateinit var instance5344: KelpBlockType

        private lateinit var instance5345: KelpBlockType

        private lateinit var instance5346: KelpBlockType

        private lateinit var instance5347: KelpBlockType

        private lateinit var instance5348: KelpBlockType

        private lateinit var instance5349: KelpBlockType

        private lateinit var instance5350: KelpBlockType

        private lateinit var instance5351: KelpBlockType

        private lateinit var instance5352: KelpBlockType

        private lateinit var instance5353: KelpBlockType

        private lateinit var instance5354: KelpBlockType

        private lateinit var instance5355: KelpBlockType

        private lateinit var instance5356: KelpBlockType

        private lateinit var instance5357: KelpBlockType

        init {
            init0()
        }

        public override val primary: KelpBlockType = instance5332

        public override val allInstances: List<KelpBlockType> =
            listOf(instance5332, instance5333, instance5334, instance5335, instance5336, instance5337, instance5338, instance5339, instance5340, instance5341, instance5342, instance5343, instance5344, instance5345, instance5346, instance5347, instance5348, instance5349, instance5350, instance5351, instance5352, instance5353, instance5354, instance5355, instance5356, instance5357)

        public fun init0() {
            instance5332 = KelpBlockType(5332.toShort(), 0)
            instance5333 = KelpBlockType(5333.toShort(), 1)
            instance5334 = KelpBlockType(5334.toShort(), 2)
            instance5335 = KelpBlockType(5335.toShort(), 3)
            instance5336 = KelpBlockType(5336.toShort(), 4)
            instance5337 = KelpBlockType(5337.toShort(), 5)
            instance5338 = KelpBlockType(5338.toShort(), 6)
            instance5339 = KelpBlockType(5339.toShort(), 7)
            instance5340 = KelpBlockType(5340.toShort(), 8)
            instance5341 = KelpBlockType(5341.toShort(), 9)
            instance5342 = KelpBlockType(5342.toShort(), 10)
            instance5343 = KelpBlockType(5343.toShort(), 11)
            instance5344 = KelpBlockType(5344.toShort(), 12)
            instance5345 = KelpBlockType(5345.toShort(), 13)
            instance5346 = KelpBlockType(5346.toShort(), 14)
            instance5347 = KelpBlockType(5347.toShort(), 15)
            instance5348 = KelpBlockType(5348.toShort(), 16)
            instance5349 = KelpBlockType(5349.toShort(), 17)
            instance5350 = KelpBlockType(5350.toShort(), 18)
            instance5351 = KelpBlockType(5351.toShort(), 19)
            instance5352 = KelpBlockType(5352.toShort(), 20)
            instance5353 = KelpBlockType(5353.toShort(), 21)
            instance5354 = KelpBlockType(5354.toShort(), 22)
            instance5355 = KelpBlockType(5355.toShort(), 23)
            instance5356 = KelpBlockType(5356.toShort(), 24)
            instance5357 = KelpBlockType(5357.toShort(), 25)
        }
    }
}
