// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class LeverBlockType private constructor(
    public override val runtimeID: Short,
    public val leverDirection: String,
    public val openBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(leverDirection: String = this.leverDirection, openBit: Byte = this.openBit):
        LeverBlockType {
        val e = LeverBlockType(0.toShort(), leverDirection, openBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: LeverBlockType): Boolean {
        var ret = true
        ret = ret && (this.leverDirection == other.leverDirection)
        ret = ret && (this.openBit == other.openBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:lever"

        public override val itemID: ItemID = ItemID(69)

        private lateinit var instance5443: LeverBlockType

        private lateinit var instance5444: LeverBlockType

        private lateinit var instance5445: LeverBlockType

        private lateinit var instance5446: LeverBlockType

        private lateinit var instance5447: LeverBlockType

        private lateinit var instance5448: LeverBlockType

        private lateinit var instance5449: LeverBlockType

        private lateinit var instance5450: LeverBlockType

        private lateinit var instance5451: LeverBlockType

        private lateinit var instance5452: LeverBlockType

        private lateinit var instance5453: LeverBlockType

        private lateinit var instance5454: LeverBlockType

        private lateinit var instance5455: LeverBlockType

        private lateinit var instance5456: LeverBlockType

        private lateinit var instance5457: LeverBlockType

        private lateinit var instance5458: LeverBlockType

        init {
            init0()
        }

        public override val primary: LeverBlockType = instance5443

        public override val allInstances: List<LeverBlockType> =
            listOf(instance5443, instance5444, instance5445, instance5446, instance5447, instance5448, instance5449, instance5450, instance5451, instance5452, instance5453, instance5454, instance5455, instance5456, instance5457, instance5458)

        public fun init0() {
            instance5443 = LeverBlockType(5443.toShort(), "down_east_west", 0.toByte())
            instance5444 = LeverBlockType(5444.toShort(), "east", 0.toByte())
            instance5445 = LeverBlockType(5445.toShort(), "west", 0.toByte())
            instance5446 = LeverBlockType(5446.toShort(), "south", 0.toByte())
            instance5447 = LeverBlockType(5447.toShort(), "north", 0.toByte())
            instance5448 = LeverBlockType(5448.toShort(), "up_north_south", 0.toByte())
            instance5449 = LeverBlockType(5449.toShort(), "up_east_west", 0.toByte())
            instance5450 = LeverBlockType(5450.toShort(), "down_north_south", 0.toByte())
            instance5451 = LeverBlockType(5451.toShort(), "down_east_west", 1.toByte())
            instance5452 = LeverBlockType(5452.toShort(), "east", 1.toByte())
            instance5453 = LeverBlockType(5453.toShort(), "west", 1.toByte())
            instance5454 = LeverBlockType(5454.toShort(), "south", 1.toByte())
            instance5455 = LeverBlockType(5455.toShort(), "north", 1.toByte())
            instance5456 = LeverBlockType(5456.toShort(), "up_north_south", 1.toByte())
            instance5457 = LeverBlockType(5457.toShort(), "up_east_west", 1.toByte())
            instance5458 = LeverBlockType(5458.toShort(), "down_north_south", 1.toByte())
        }
    }
}
