// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class LightGrayCandleCakeBlockType private constructor(
    public override val runtimeID: Short,
    public val lit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(lit: Byte = this.lit): LightGrayCandleCakeBlockType {
        val e = LightGrayCandleCakeBlockType(0.toShort(), lit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: LightGrayCandleCakeBlockType): Boolean {
        var ret = true
        ret = ret && (this.lit == other.lit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:light_gray_candle_cake"

        public override val itemID: ItemID = ItemID(-438)

        private lateinit var instance5499: LightGrayCandleCakeBlockType

        private lateinit var instance5500: LightGrayCandleCakeBlockType

        init {
            init0()
        }

        public override val primary: LightGrayCandleCakeBlockType = instance5499

        public override val allInstances: List<LightGrayCandleCakeBlockType> =
            listOf(instance5499, instance5500)

        public fun init0() {
            instance5499 = LightGrayCandleCakeBlockType(5499.toShort(), 0.toByte())
            instance5500 = LightGrayCandleCakeBlockType(5500.toShort(), 1.toByte())
        }
    }
}
