// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class MysteriousFrameBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): MysteriousFrameBlockType {
        val e = MysteriousFrameBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: MysteriousFrameBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:mysterious_frame"

        public override val itemID: ItemID = ItemID(-466)

        private lateinit var instance5687: MysteriousFrameBlockType

        init {
            init0()
        }

        public override val primary: MysteriousFrameBlockType = instance5687

        public override val allInstances: List<MysteriousFrameBlockType> = listOf(instance5687)

        public fun init0() {
            instance5687 = MysteriousFrameBlockType(5687.toShort())
        }
    }
}
