// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class NetherBrickFenceBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): NetherBrickFenceBlockType {
        val e = NetherBrickFenceBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: NetherBrickFenceBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:nether_brick_fence"

        public override val itemID: ItemID = ItemID(113)

        private lateinit var instance5690: NetherBrickFenceBlockType

        init {
            init0()
        }

        public override val primary: NetherBrickFenceBlockType = instance5690

        public override val allInstances: List<NetherBrickFenceBlockType> = listOf(instance5690)

        public fun init0() {
            instance5690 = NetherBrickFenceBlockType(5690.toShort())
        }
    }
}
