// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class NormalStoneStairsBlockType private constructor(
    public override val runtimeID: Short,
    public val upsideDownBit: Byte,
    public val weirdoDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        upsideDownBit: Byte = this.upsideDownBit,
        weirdoDirection: Int =
            this.weirdoDirection
    ): NormalStoneStairsBlockType {
        val e = NormalStoneStairsBlockType(0.toShort(), upsideDownBit, weirdoDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: NormalStoneStairsBlockType): Boolean {
        var ret = true
        ret = ret && (this.upsideDownBit == other.upsideDownBit)
        ret = ret && (this.weirdoDirection == other.weirdoDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:normal_stone_stairs"

        public override val itemID: ItemID = ItemID(-180)

        private lateinit var instance5709: NormalStoneStairsBlockType

        private lateinit var instance5710: NormalStoneStairsBlockType

        private lateinit var instance5711: NormalStoneStairsBlockType

        private lateinit var instance5712: NormalStoneStairsBlockType

        private lateinit var instance5713: NormalStoneStairsBlockType

        private lateinit var instance5714: NormalStoneStairsBlockType

        private lateinit var instance5715: NormalStoneStairsBlockType

        private lateinit var instance5716: NormalStoneStairsBlockType

        init {
            init0()
        }

        public override val primary: NormalStoneStairsBlockType = instance5709

        public override val allInstances: List<NormalStoneStairsBlockType> =
            listOf(instance5709, instance5710, instance5711, instance5712, instance5713, instance5714, instance5715, instance5716)

        public fun init0() {
            instance5709 = NormalStoneStairsBlockType(5709.toShort(), 0.toByte(), 0)
            instance5710 = NormalStoneStairsBlockType(5710.toShort(), 0.toByte(), 1)
            instance5711 = NormalStoneStairsBlockType(5711.toShort(), 0.toByte(), 2)
            instance5712 = NormalStoneStairsBlockType(5712.toShort(), 0.toByte(), 3)
            instance5713 = NormalStoneStairsBlockType(5713.toShort(), 1.toByte(), 0)
            instance5714 = NormalStoneStairsBlockType(5714.toShort(), 1.toByte(), 1)
            instance5715 = NormalStoneStairsBlockType(5715.toShort(), 1.toByte(), 2)
            instance5716 = NormalStoneStairsBlockType(5716.toShort(), 1.toByte(), 3)
        }
    }
}
