// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class PistonBlockType private constructor(
    public override val runtimeID: Short,
    public val facingDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(facingDirection: Int = this.facingDirection): PistonBlockType {
        val e = PistonBlockType(0.toShort(), facingDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: PistonBlockType): Boolean {
        var ret = true
        ret = ret && (this.facingDirection == other.facingDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:piston"

        public override val itemID: ItemID = ItemID(33)

        private lateinit var instance5788: PistonBlockType

        private lateinit var instance5789: PistonBlockType

        private lateinit var instance5790: PistonBlockType

        private lateinit var instance5791: PistonBlockType

        private lateinit var instance5792: PistonBlockType

        private lateinit var instance5793: PistonBlockType

        init {
            init0()
        }

        public override val primary: PistonBlockType = instance5788

        public override val allInstances: List<PistonBlockType> =
            listOf(instance5788, instance5789, instance5790, instance5791, instance5792, instance5793)

        public fun init0() {
            instance5788 = PistonBlockType(5788.toShort(), 0)
            instance5789 = PistonBlockType(5789.toShort(), 1)
            instance5790 = PistonBlockType(5790.toShort(), 2)
            instance5791 = PistonBlockType(5791.toShort(), 3)
            instance5792 = PistonBlockType(5792.toShort(), 4)
            instance5793 = PistonBlockType(5793.toShort(), 5)
        }
    }
}
