// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class PodzolBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): PodzolBlockType {
        val e = PodzolBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: PodzolBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:podzol"

        public override val itemID: ItemID = ItemID(243)

        private lateinit var instance5806: PodzolBlockType

        init {
            init0()
        }

        public override val primary: PodzolBlockType = instance5806

        public override val allInstances: List<PodzolBlockType> = listOf(instance5806)

        public fun init0() {
            instance5806 = PodzolBlockType(5806.toShort())
        }
    }
}
