// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class PolishedBlackstoneBrickStairsBlockType private constructor(
    public override val runtimeID: Short,
    public val upsideDownBit: Byte,
    public val weirdoDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        upsideDownBit: Byte = this.upsideDownBit,
        weirdoDirection: Int =
            this.weirdoDirection
    ): PolishedBlackstoneBrickStairsBlockType {
        val e = PolishedBlackstoneBrickStairsBlockType(0.toShort(), upsideDownBit, weirdoDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: PolishedBlackstoneBrickStairsBlockType): Boolean {
        var ret = true
        ret = ret && (this.upsideDownBit == other.upsideDownBit)
        ret = ret && (this.weirdoDirection == other.weirdoDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:polished_blackstone_brick_stairs"

        public override val itemID: ItemID = ItemID(-275)

        private lateinit var instance5833: PolishedBlackstoneBrickStairsBlockType

        private lateinit var instance5834: PolishedBlackstoneBrickStairsBlockType

        private lateinit var instance5835: PolishedBlackstoneBrickStairsBlockType

        private lateinit var instance5836: PolishedBlackstoneBrickStairsBlockType

        private lateinit var instance5837: PolishedBlackstoneBrickStairsBlockType

        private lateinit var instance5838: PolishedBlackstoneBrickStairsBlockType

        private lateinit var instance5839: PolishedBlackstoneBrickStairsBlockType

        private lateinit var instance5840: PolishedBlackstoneBrickStairsBlockType

        init {
            init0()
        }

        public override val primary: PolishedBlackstoneBrickStairsBlockType = instance5833

        public override val allInstances: List<PolishedBlackstoneBrickStairsBlockType> =
            listOf(instance5833, instance5834, instance5835, instance5836, instance5837, instance5838, instance5839, instance5840)

        public fun init0() {
            instance5833 = PolishedBlackstoneBrickStairsBlockType(5833.toShort(), 0.toByte(), 0)
            instance5834 = PolishedBlackstoneBrickStairsBlockType(5834.toShort(), 0.toByte(), 1)
            instance5835 = PolishedBlackstoneBrickStairsBlockType(5835.toShort(), 0.toByte(), 2)
            instance5836 = PolishedBlackstoneBrickStairsBlockType(5836.toShort(), 0.toByte(), 3)
            instance5837 = PolishedBlackstoneBrickStairsBlockType(5837.toShort(), 1.toByte(), 0)
            instance5838 = PolishedBlackstoneBrickStairsBlockType(5838.toShort(), 1.toByte(), 1)
            instance5839 = PolishedBlackstoneBrickStairsBlockType(5839.toShort(), 1.toByte(), 2)
            instance5840 = PolishedBlackstoneBrickStairsBlockType(5840.toShort(), 1.toByte(), 3)
        }
    }
}
