// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class PolishedDioriteStairsBlockType private constructor(
    public override val runtimeID: Short,
    public val upsideDownBit: Byte,
    public val weirdoDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        upsideDownBit: Byte = this.upsideDownBit,
        weirdoDirection: Int =
            this.weirdoDirection
    ): PolishedDioriteStairsBlockType {
        val e = PolishedDioriteStairsBlockType(0.toShort(), upsideDownBit, weirdoDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: PolishedDioriteStairsBlockType): Boolean {
        var ret = true
        ret = ret && (this.upsideDownBit == other.upsideDownBit)
        ret = ret && (this.weirdoDirection == other.weirdoDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:polished_diorite_stairs"

        public override val itemID: ItemID = ItemID(-173)

        private lateinit var instance6381: PolishedDioriteStairsBlockType

        private lateinit var instance6382: PolishedDioriteStairsBlockType

        private lateinit var instance6383: PolishedDioriteStairsBlockType

        private lateinit var instance6384: PolishedDioriteStairsBlockType

        private lateinit var instance6385: PolishedDioriteStairsBlockType

        private lateinit var instance6386: PolishedDioriteStairsBlockType

        private lateinit var instance6387: PolishedDioriteStairsBlockType

        private lateinit var instance6388: PolishedDioriteStairsBlockType

        init {
            init0()
        }

        public override val primary: PolishedDioriteStairsBlockType = instance6381

        public override val allInstances: List<PolishedDioriteStairsBlockType> =
            listOf(instance6381, instance6382, instance6383, instance6384, instance6385, instance6386, instance6387, instance6388)

        public fun init0() {
            instance6381 = PolishedDioriteStairsBlockType(6381.toShort(), 0.toByte(), 0)
            instance6382 = PolishedDioriteStairsBlockType(6382.toShort(), 0.toByte(), 1)
            instance6383 = PolishedDioriteStairsBlockType(6383.toShort(), 0.toByte(), 2)
            instance6384 = PolishedDioriteStairsBlockType(6384.toShort(), 0.toByte(), 3)
            instance6385 = PolishedDioriteStairsBlockType(6385.toShort(), 1.toByte(), 0)
            instance6386 = PolishedDioriteStairsBlockType(6386.toShort(), 1.toByte(), 1)
            instance6387 = PolishedDioriteStairsBlockType(6387.toShort(), 1.toByte(), 2)
            instance6388 = PolishedDioriteStairsBlockType(6388.toShort(), 1.toByte(), 3)
        }
    }
}
