// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class RedGlazedTerracottaBlockType private constructor(
    public override val runtimeID: Short,
    public val facingDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(facingDirection: Int = this.facingDirection): RedGlazedTerracottaBlockType {
        val e = RedGlazedTerracottaBlockType(0.toShort(), facingDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: RedGlazedTerracottaBlockType): Boolean {
        var ret = true
        ret = ret && (this.facingDirection == other.facingDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:red_glazed_terracotta"

        public override val itemID: ItemID = ItemID(234)

        private lateinit var instance6604: RedGlazedTerracottaBlockType

        private lateinit var instance6605: RedGlazedTerracottaBlockType

        private lateinit var instance6606: RedGlazedTerracottaBlockType

        private lateinit var instance6607: RedGlazedTerracottaBlockType

        private lateinit var instance6608: RedGlazedTerracottaBlockType

        private lateinit var instance6609: RedGlazedTerracottaBlockType

        init {
            init0()
        }

        public override val primary: RedGlazedTerracottaBlockType = instance6604

        public override val allInstances: List<RedGlazedTerracottaBlockType> =
            listOf(instance6604, instance6605, instance6606, instance6607, instance6608, instance6609)

        public fun init0() {
            instance6604 = RedGlazedTerracottaBlockType(6604.toShort(), 0)
            instance6605 = RedGlazedTerracottaBlockType(6605.toShort(), 1)
            instance6606 = RedGlazedTerracottaBlockType(6606.toShort(), 2)
            instance6607 = RedGlazedTerracottaBlockType(6607.toShort(), 3)
            instance6608 = RedGlazedTerracottaBlockType(6608.toShort(), 4)
            instance6609 = RedGlazedTerracottaBlockType(6609.toShort(), 5)
        }
    }
}
