// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class RedstoneBlockBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): RedstoneBlockBlockType {
        val e = RedstoneBlockBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: RedstoneBlockBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:redstone_block"

        public override val itemID: ItemID = ItemID(152)

        private lateinit var instance6648: RedstoneBlockBlockType

        init {
            init0()
        }

        public override val primary: RedstoneBlockBlockType = instance6648

        public override val allInstances: List<RedstoneBlockBlockType> = listOf(instance6648)

        public fun init0() {
            instance6648 = RedstoneBlockBlockType(6648.toShort())
        }
    }
}
