// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class SculkShriekerBlockType private constructor(
    public override val runtimeID: Short,
    public val active: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(active: Byte = this.active): SculkShriekerBlockType {
        val e = SculkShriekerBlockType(0.toShort(), active)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: SculkShriekerBlockType): Boolean {
        var ret = true
        ret = ret && (this.active == other.active)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:sculk_shrieker"

        public override val itemID: ItemID = ItemID(-461)

        private lateinit var instance6754: SculkShriekerBlockType

        private lateinit var instance6755: SculkShriekerBlockType

        init {
            init0()
        }

        public override val primary: SculkShriekerBlockType = instance6754

        public override val allInstances: List<SculkShriekerBlockType> =
            listOf(instance6754, instance6755)

        public fun init0() {
            instance6754 = SculkShriekerBlockType(6754.toShort(), 0.toByte())
            instance6755 = SculkShriekerBlockType(6755.toShort(), 1.toByte())
        }
    }
}
