// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class SeaPickleBlockType private constructor(
    public override val runtimeID: Short,
    public val clusterCount: Int,
    public val deadBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(clusterCount: Int = this.clusterCount, deadBit: Byte = this.deadBit):
        SeaPickleBlockType {
        val e = SeaPickleBlockType(0.toShort(), clusterCount, deadBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: SeaPickleBlockType): Boolean {
        var ret = true
        ret = ret && (this.clusterCount == other.clusterCount)
        ret = ret && (this.deadBit == other.deadBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:sea_pickle"

        public override val itemID: ItemID = ItemID(-156)

        private lateinit var instance6820: SeaPickleBlockType

        private lateinit var instance6821: SeaPickleBlockType

        private lateinit var instance6822: SeaPickleBlockType

        private lateinit var instance6823: SeaPickleBlockType

        private lateinit var instance6824: SeaPickleBlockType

        private lateinit var instance6825: SeaPickleBlockType

        private lateinit var instance6826: SeaPickleBlockType

        private lateinit var instance6827: SeaPickleBlockType

        init {
            init0()
        }

        public override val primary: SeaPickleBlockType = instance6820

        public override val allInstances: List<SeaPickleBlockType> =
            listOf(instance6820, instance6821, instance6822, instance6823, instance6824, instance6825, instance6826, instance6827)

        public fun init0() {
            instance6820 = SeaPickleBlockType(6820.toShort(), 0, 0.toByte())
            instance6821 = SeaPickleBlockType(6821.toShort(), 1, 0.toByte())
            instance6822 = SeaPickleBlockType(6822.toShort(), 2, 0.toByte())
            instance6823 = SeaPickleBlockType(6823.toShort(), 3, 0.toByte())
            instance6824 = SeaPickleBlockType(6824.toShort(), 0, 1.toByte())
            instance6825 = SeaPickleBlockType(6825.toShort(), 1, 1.toByte())
            instance6826 = SeaPickleBlockType(6826.toShort(), 2, 1.toByte())
            instance6827 = SeaPickleBlockType(6827.toShort(), 3, 1.toByte())
        }
    }
}
