// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class SkullBlockType private constructor(
    public override val runtimeID: Short,
    public val facingDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(facingDirection: Int = this.facingDirection): SkullBlockType {
        val e = SkullBlockType(0.toShort(), facingDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: SkullBlockType): Boolean {
        var ret = true
        ret = ret && (this.facingDirection == other.facingDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:skull"

        public override val itemID: ItemID = ItemID(144)

        private lateinit var instance6855: SkullBlockType

        private lateinit var instance6856: SkullBlockType

        private lateinit var instance6857: SkullBlockType

        private lateinit var instance6858: SkullBlockType

        private lateinit var instance6859: SkullBlockType

        private lateinit var instance6860: SkullBlockType

        init {
            init0()
        }

        public override val primary: SkullBlockType = instance6855

        public override val allInstances: List<SkullBlockType> =
            listOf(instance6855, instance6856, instance6857, instance6858, instance6859, instance6860)

        public fun init0() {
            instance6855 = SkullBlockType(6855.toShort(), 0)
            instance6856 = SkullBlockType(6856.toShort(), 1)
            instance6857 = SkullBlockType(6857.toShort(), 2)
            instance6858 = SkullBlockType(6858.toShort(), 3)
            instance6859 = SkullBlockType(6859.toShort(), 4)
            instance6860 = SkullBlockType(6860.toShort(), 5)
        }
    }
}
