// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class SmallDripleafBlockBlockType private constructor(
    public override val runtimeID: Short,
    public val direction: Int,
    public val upperBlockBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(direction: Int = this.direction, upperBlockBit: Byte = this.upperBlockBit):
        SmallDripleafBlockBlockType {
        val e = SmallDripleafBlockBlockType(0.toShort(), direction, upperBlockBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: SmallDripleafBlockBlockType): Boolean {
        var ret = true
        ret = ret && (this.direction == other.direction)
        ret = ret && (this.upperBlockBit == other.upperBlockBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:small_dripleaf_block"

        public override val itemID: ItemID = ItemID(-336)

        private lateinit var instance6868: SmallDripleafBlockBlockType

        private lateinit var instance6869: SmallDripleafBlockBlockType

        private lateinit var instance6870: SmallDripleafBlockBlockType

        private lateinit var instance6871: SmallDripleafBlockBlockType

        private lateinit var instance6872: SmallDripleafBlockBlockType

        private lateinit var instance6873: SmallDripleafBlockBlockType

        private lateinit var instance6874: SmallDripleafBlockBlockType

        private lateinit var instance6875: SmallDripleafBlockBlockType

        init {
            init0()
        }

        public override val primary: SmallDripleafBlockBlockType = instance6868

        public override val allInstances: List<SmallDripleafBlockBlockType> =
            listOf(instance6868, instance6869, instance6870, instance6871, instance6872, instance6873, instance6874, instance6875)

        public fun init0() {
            instance6868 = SmallDripleafBlockBlockType(6868.toShort(), 0, 0.toByte())
            instance6869 = SmallDripleafBlockBlockType(6869.toShort(), 0, 1.toByte())
            instance6870 = SmallDripleafBlockBlockType(6870.toShort(), 1, 0.toByte())
            instance6871 = SmallDripleafBlockBlockType(6871.toShort(), 1, 1.toByte())
            instance6872 = SmallDripleafBlockBlockType(6872.toShort(), 2, 0.toByte())
            instance6873 = SmallDripleafBlockBlockType(6873.toShort(), 2, 1.toByte())
            instance6874 = SmallDripleafBlockBlockType(6874.toShort(), 3, 0.toByte())
            instance6875 = SmallDripleafBlockBlockType(6875.toShort(), 3, 1.toByte())
        }
    }
}
