// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class SmithingTableBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): SmithingTableBlockType {
        val e = SmithingTableBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: SmithingTableBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:smithing_table"

        public override val itemID: ItemID = ItemID(-202)

        private lateinit var instance6876: SmithingTableBlockType

        init {
            init0()
        }

        public override val primary: SmithingTableBlockType = instance6876

        public override val allInstances: List<SmithingTableBlockType> = listOf(instance6876)

        public fun init0() {
            instance6876 = SmithingTableBlockType(6876.toShort())
        }
    }
}
