// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class SmoothStoneBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): SmoothStoneBlockType {
        val e = SmoothStoneBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: SmoothStoneBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:smooth_stone"

        public override val itemID: ItemID = ItemID(-183)

        private lateinit var instance6908: SmoothStoneBlockType

        init {
            init0()
        }

        public override val primary: SmoothStoneBlockType = instance6908

        public override val allInstances: List<SmoothStoneBlockType> = listOf(instance6908)

        public fun init0() {
            instance6908 = SmoothStoneBlockType(6908.toShort())
        }
    }
}
