// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class SoulSoilBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): SoulSoilBlockType {
        val e = SoulSoilBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: SoulSoilBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:soul_soil"

        public override val itemID: ItemID = ItemID(-236)

        private lateinit var instance6953: SoulSoilBlockType

        init {
            init0()
        }

        public override val primary: SoulSoilBlockType = instance6953

        public override val allInstances: List<SoulSoilBlockType> = listOf(instance6953)

        public fun init0() {
            instance6953 = SoulSoilBlockType(6953.toShort())
        }
    }
}
