// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class StoneSlab2BlockType private constructor(
    public override val runtimeID: Short,
    public val stoneSlabType2: String,
    public val topSlotBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(stoneSlabType2: String = this.stoneSlabType2, topSlotBit: Byte = this.topSlotBit):
        StoneSlab2BlockType {
        val e = StoneSlab2BlockType(0.toShort(), stoneSlabType2, topSlotBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: StoneSlab2BlockType): Boolean {
        var ret = true
        ret = ret && (this.stoneSlabType2 == other.stoneSlabType2)
        ret = ret && (this.topSlotBit == other.topSlotBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:stone_slab2"

        public override val itemID: ItemID = ItemID(0)

        private lateinit var instance7236: StoneSlab2BlockType

        private lateinit var instance7237: StoneSlab2BlockType

        private lateinit var instance7238: StoneSlab2BlockType

        private lateinit var instance7239: StoneSlab2BlockType

        private lateinit var instance7240: StoneSlab2BlockType

        private lateinit var instance7241: StoneSlab2BlockType

        private lateinit var instance7242: StoneSlab2BlockType

        private lateinit var instance7243: StoneSlab2BlockType

        private lateinit var instance7244: StoneSlab2BlockType

        private lateinit var instance7245: StoneSlab2BlockType

        private lateinit var instance7246: StoneSlab2BlockType

        private lateinit var instance7247: StoneSlab2BlockType

        private lateinit var instance7248: StoneSlab2BlockType

        private lateinit var instance7249: StoneSlab2BlockType

        private lateinit var instance7250: StoneSlab2BlockType

        private lateinit var instance7251: StoneSlab2BlockType

        init {
            init0()
        }

        public override val primary: StoneSlab2BlockType = instance7236

        public override val allInstances: List<StoneSlab2BlockType> =
            listOf(instance7236, instance7237, instance7238, instance7239, instance7240, instance7241, instance7242, instance7243, instance7244, instance7245, instance7246, instance7247, instance7248, instance7249, instance7250, instance7251)

        public fun init0() {
            instance7236 = StoneSlab2BlockType(7236.toShort(), "red_sandstone", 0.toByte())
            instance7237 = StoneSlab2BlockType(7237.toShort(), "purpur", 0.toByte())
            instance7238 = StoneSlab2BlockType(7238.toShort(), "prismarine_rough", 0.toByte())
            instance7239 = StoneSlab2BlockType(7239.toShort(), "prismarine_dark", 0.toByte())
            instance7240 = StoneSlab2BlockType(7240.toShort(), "prismarine_brick", 0.toByte())
            instance7241 = StoneSlab2BlockType(7241.toShort(), "mossy_cobblestone", 0.toByte())
            instance7242 = StoneSlab2BlockType(7242.toShort(), "smooth_sandstone", 0.toByte())
            instance7243 = StoneSlab2BlockType(7243.toShort(), "red_nether_brick", 0.toByte())
            instance7244 = StoneSlab2BlockType(7244.toShort(), "red_sandstone", 1.toByte())
            instance7245 = StoneSlab2BlockType(7245.toShort(), "purpur", 1.toByte())
            instance7246 = StoneSlab2BlockType(7246.toShort(), "prismarine_rough", 1.toByte())
            instance7247 = StoneSlab2BlockType(7247.toShort(), "prismarine_dark", 1.toByte())
            instance7248 = StoneSlab2BlockType(7248.toShort(), "prismarine_brick", 1.toByte())
            instance7249 = StoneSlab2BlockType(7249.toShort(), "mossy_cobblestone", 1.toByte())
            instance7250 = StoneSlab2BlockType(7250.toShort(), "smooth_sandstone", 1.toByte())
            instance7251 = StoneSlab2BlockType(7251.toShort(), "red_nether_brick", 1.toByte())
        }
    }
}
