// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class StoneStairsBlockType private constructor(
    public override val runtimeID: Short,
    public val upsideDownBit: Byte,
    public val weirdoDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        upsideDownBit: Byte = this.upsideDownBit,
        weirdoDirection: Int =
            this.weirdoDirection
    ): StoneStairsBlockType {
        val e = StoneStairsBlockType(0.toShort(), upsideDownBit, weirdoDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: StoneStairsBlockType): Boolean {
        var ret = true
        ret = ret && (this.upsideDownBit == other.upsideDownBit)
        ret = ret && (this.weirdoDirection == other.weirdoDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:stone_stairs"

        public override val itemID: ItemID = ItemID(67)

        private lateinit var instance7278: StoneStairsBlockType

        private lateinit var instance7279: StoneStairsBlockType

        private lateinit var instance7280: StoneStairsBlockType

        private lateinit var instance7281: StoneStairsBlockType

        private lateinit var instance7282: StoneStairsBlockType

        private lateinit var instance7283: StoneStairsBlockType

        private lateinit var instance7284: StoneStairsBlockType

        private lateinit var instance7285: StoneStairsBlockType

        init {
            init0()
        }

        public override val primary: StoneStairsBlockType = instance7278

        public override val allInstances: List<StoneStairsBlockType> =
            listOf(instance7278, instance7279, instance7280, instance7281, instance7282, instance7283, instance7284, instance7285)

        public fun init0() {
            instance7278 = StoneStairsBlockType(7278.toShort(), 0.toByte(), 0)
            instance7279 = StoneStairsBlockType(7279.toShort(), 0.toByte(), 1)
            instance7280 = StoneStairsBlockType(7280.toShort(), 0.toByte(), 2)
            instance7281 = StoneStairsBlockType(7281.toShort(), 0.toByte(), 3)
            instance7282 = StoneStairsBlockType(7282.toShort(), 1.toByte(), 0)
            instance7283 = StoneStairsBlockType(7283.toShort(), 1.toByte(), 1)
            instance7284 = StoneStairsBlockType(7284.toShort(), 1.toByte(), 2)
            instance7285 = StoneStairsBlockType(7285.toShort(), 1.toByte(), 3)
        }
    }
}
