// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class TrapdoorBlockType private constructor(
    public override val runtimeID: Short,
    public val direction: Int,
    public val openBit: Byte,
    public val upsideDownBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        direction: Int = this.direction,
        openBit: Byte = this.openBit,
        upsideDownBit: Byte = this.upsideDownBit
    ): TrapdoorBlockType {
        val e = TrapdoorBlockType(0.toShort(), direction, openBit, upsideDownBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: TrapdoorBlockType): Boolean {
        var ret = true
        ret = ret && (this.direction == other.direction)
        ret = ret && (this.openBit == other.openBit)
        ret = ret && (this.upsideDownBit == other.upsideDownBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:trapdoor"

        public override val itemID: ItemID = ItemID(96)

        private lateinit var instance7360: TrapdoorBlockType

        private lateinit var instance7361: TrapdoorBlockType

        private lateinit var instance7362: TrapdoorBlockType

        private lateinit var instance7363: TrapdoorBlockType

        private lateinit var instance7364: TrapdoorBlockType

        private lateinit var instance7365: TrapdoorBlockType

        private lateinit var instance7366: TrapdoorBlockType

        private lateinit var instance7367: TrapdoorBlockType

        private lateinit var instance7368: TrapdoorBlockType

        private lateinit var instance7369: TrapdoorBlockType

        private lateinit var instance7370: TrapdoorBlockType

        private lateinit var instance7371: TrapdoorBlockType

        private lateinit var instance7372: TrapdoorBlockType

        private lateinit var instance7373: TrapdoorBlockType

        private lateinit var instance7374: TrapdoorBlockType

        private lateinit var instance7375: TrapdoorBlockType

        init {
            init0()
        }

        public override val primary: TrapdoorBlockType = instance7360

        public override val allInstances: List<TrapdoorBlockType> =
            listOf(instance7360, instance7361, instance7362, instance7363, instance7364, instance7365, instance7366, instance7367, instance7368, instance7369, instance7370, instance7371, instance7372, instance7373, instance7374, instance7375)

        public fun init0() {
            instance7360 = TrapdoorBlockType(7360.toShort(), 0, 0.toByte(), 0.toByte())
            instance7361 = TrapdoorBlockType(7361.toShort(), 1, 0.toByte(), 0.toByte())
            instance7362 = TrapdoorBlockType(7362.toShort(), 2, 0.toByte(), 0.toByte())
            instance7363 = TrapdoorBlockType(7363.toShort(), 3, 0.toByte(), 0.toByte())
            instance7364 = TrapdoorBlockType(7364.toShort(), 0, 0.toByte(), 1.toByte())
            instance7365 = TrapdoorBlockType(7365.toShort(), 1, 0.toByte(), 1.toByte())
            instance7366 = TrapdoorBlockType(7366.toShort(), 2, 0.toByte(), 1.toByte())
            instance7367 = TrapdoorBlockType(7367.toShort(), 3, 0.toByte(), 1.toByte())
            instance7368 = TrapdoorBlockType(7368.toShort(), 0, 1.toByte(), 0.toByte())
            instance7369 = TrapdoorBlockType(7369.toShort(), 1, 1.toByte(), 0.toByte())
            instance7370 = TrapdoorBlockType(7370.toShort(), 2, 1.toByte(), 0.toByte())
            instance7371 = TrapdoorBlockType(7371.toShort(), 3, 1.toByte(), 0.toByte())
            instance7372 = TrapdoorBlockType(7372.toShort(), 0, 1.toByte(), 1.toByte())
            instance7373 = TrapdoorBlockType(7373.toShort(), 1, 1.toByte(), 1.toByte())
            instance7374 = TrapdoorBlockType(7374.toShort(), 2, 1.toByte(), 1.toByte())
            instance7375 = TrapdoorBlockType(7375.toShort(), 3, 1.toByte(), 1.toByte())
        }
    }
}
