// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class TwistingVinesBlockType private constructor(
    public override val runtimeID: Short,
    public val twistingVinesAge: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(twistingVinesAge: Int = this.twistingVinesAge): TwistingVinesBlockType {
        val e = TwistingVinesBlockType(0.toShort(), twistingVinesAge)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: TwistingVinesBlockType): Boolean {
        var ret = true
        ret = ret && (this.twistingVinesAge == other.twistingVinesAge)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:twisting_vines"

        public override val itemID: ItemID = ItemID(-287)

        private lateinit var instance7427: TwistingVinesBlockType

        private lateinit var instance7428: TwistingVinesBlockType

        private lateinit var instance7429: TwistingVinesBlockType

        private lateinit var instance7430: TwistingVinesBlockType

        private lateinit var instance7431: TwistingVinesBlockType

        private lateinit var instance7432: TwistingVinesBlockType

        private lateinit var instance7433: TwistingVinesBlockType

        private lateinit var instance7434: TwistingVinesBlockType

        private lateinit var instance7435: TwistingVinesBlockType

        private lateinit var instance7436: TwistingVinesBlockType

        private lateinit var instance7437: TwistingVinesBlockType

        private lateinit var instance7438: TwistingVinesBlockType

        private lateinit var instance7439: TwistingVinesBlockType

        private lateinit var instance7440: TwistingVinesBlockType

        private lateinit var instance7441: TwistingVinesBlockType

        private lateinit var instance7442: TwistingVinesBlockType

        private lateinit var instance7443: TwistingVinesBlockType

        private lateinit var instance7444: TwistingVinesBlockType

        private lateinit var instance7445: TwistingVinesBlockType

        private lateinit var instance7446: TwistingVinesBlockType

        private lateinit var instance7447: TwistingVinesBlockType

        private lateinit var instance7448: TwistingVinesBlockType

        private lateinit var instance7449: TwistingVinesBlockType

        private lateinit var instance7450: TwistingVinesBlockType

        private lateinit var instance7451: TwistingVinesBlockType

        private lateinit var instance7452: TwistingVinesBlockType

        init {
            init0()
        }

        public override val primary: TwistingVinesBlockType = instance7427

        public override val allInstances: List<TwistingVinesBlockType> =
            listOf(instance7427, instance7428, instance7429, instance7430, instance7431, instance7432, instance7433, instance7434, instance7435, instance7436, instance7437, instance7438, instance7439, instance7440, instance7441, instance7442, instance7443, instance7444, instance7445, instance7446, instance7447, instance7448, instance7449, instance7450, instance7451, instance7452)

        public fun init0() {
            instance7427 = TwistingVinesBlockType(7427.toShort(), 0)
            instance7428 = TwistingVinesBlockType(7428.toShort(), 1)
            instance7429 = TwistingVinesBlockType(7429.toShort(), 2)
            instance7430 = TwistingVinesBlockType(7430.toShort(), 3)
            instance7431 = TwistingVinesBlockType(7431.toShort(), 4)
            instance7432 = TwistingVinesBlockType(7432.toShort(), 5)
            instance7433 = TwistingVinesBlockType(7433.toShort(), 6)
            instance7434 = TwistingVinesBlockType(7434.toShort(), 7)
            instance7435 = TwistingVinesBlockType(7435.toShort(), 8)
            instance7436 = TwistingVinesBlockType(7436.toShort(), 9)
            instance7437 = TwistingVinesBlockType(7437.toShort(), 10)
            instance7438 = TwistingVinesBlockType(7438.toShort(), 11)
            instance7439 = TwistingVinesBlockType(7439.toShort(), 12)
            instance7440 = TwistingVinesBlockType(7440.toShort(), 13)
            instance7441 = TwistingVinesBlockType(7441.toShort(), 14)
            instance7442 = TwistingVinesBlockType(7442.toShort(), 15)
            instance7443 = TwistingVinesBlockType(7443.toShort(), 16)
            instance7444 = TwistingVinesBlockType(7444.toShort(), 17)
            instance7445 = TwistingVinesBlockType(7445.toShort(), 18)
            instance7446 = TwistingVinesBlockType(7446.toShort(), 19)
            instance7447 = TwistingVinesBlockType(7447.toShort(), 20)
            instance7448 = TwistingVinesBlockType(7448.toShort(), 21)
            instance7449 = TwistingVinesBlockType(7449.toShort(), 22)
            instance7450 = TwistingVinesBlockType(7450.toShort(), 23)
            instance7451 = TwistingVinesBlockType(7451.toShort(), 24)
            instance7452 = TwistingVinesBlockType(7452.toShort(), 25)
        }
    }
}
