// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class WaterBlockType private constructor(
    public override val runtimeID: Short,
    public val liquidDepth: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(liquidDepth: Int = this.liquidDepth): WaterBlockType {
        val e = WaterBlockType(0.toShort(), liquidDepth)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: WaterBlockType): Boolean {
        var ret = true
        ret = ret && (this.liquidDepth == other.liquidDepth)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:water"

        public override val itemID: ItemID = ItemID(9)

        private lateinit var instance7666: WaterBlockType

        private lateinit var instance7667: WaterBlockType

        private lateinit var instance7668: WaterBlockType

        private lateinit var instance7669: WaterBlockType

        private lateinit var instance7670: WaterBlockType

        private lateinit var instance7671: WaterBlockType

        private lateinit var instance7672: WaterBlockType

        private lateinit var instance7673: WaterBlockType

        private lateinit var instance7674: WaterBlockType

        private lateinit var instance7675: WaterBlockType

        private lateinit var instance7676: WaterBlockType

        private lateinit var instance7677: WaterBlockType

        private lateinit var instance7678: WaterBlockType

        private lateinit var instance7679: WaterBlockType

        private lateinit var instance7680: WaterBlockType

        private lateinit var instance7681: WaterBlockType

        init {
            init0()
        }

        public override val primary: WaterBlockType = instance7666

        public override val allInstances: List<WaterBlockType> =
            listOf(instance7666, instance7667, instance7668, instance7669, instance7670, instance7671, instance7672, instance7673, instance7674, instance7675, instance7676, instance7677, instance7678, instance7679, instance7680, instance7681)

        public fun init0() {
            instance7666 = WaterBlockType(7666.toShort(), 0)
            instance7667 = WaterBlockType(7667.toShort(), 1)
            instance7668 = WaterBlockType(7668.toShort(), 2)
            instance7669 = WaterBlockType(7669.toShort(), 3)
            instance7670 = WaterBlockType(7670.toShort(), 4)
            instance7671 = WaterBlockType(7671.toShort(), 5)
            instance7672 = WaterBlockType(7672.toShort(), 6)
            instance7673 = WaterBlockType(7673.toShort(), 7)
            instance7674 = WaterBlockType(7674.toShort(), 8)
            instance7675 = WaterBlockType(7675.toShort(), 9)
            instance7676 = WaterBlockType(7676.toShort(), 10)
            instance7677 = WaterBlockType(7677.toShort(), 11)
            instance7678 = WaterBlockType(7678.toShort(), 12)
            instance7679 = WaterBlockType(7679.toShort(), 13)
            instance7680 = WaterBlockType(7680.toShort(), 14)
            instance7681 = WaterBlockType(7681.toShort(), 15)
        }
    }
}
