// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class WaxedOxidizedCopperBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): WaxedOxidizedCopperBlockType {
        val e = WaxedOxidizedCopperBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: WaxedOxidizedCopperBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:waxed_oxidized_copper"

        public override val itemID: ItemID = ItemID(-446)

        private lateinit var instance7711: WaxedOxidizedCopperBlockType

        init {
            init0()
        }

        public override val primary: WaxedOxidizedCopperBlockType = instance7711

        public override val allInstances: List<WaxedOxidizedCopperBlockType> = listOf(instance7711)

        public fun init0() {
            instance7711 = WaxedOxidizedCopperBlockType(7711.toShort())
        }
    }
}
