// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class WaxedCutCopperBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): WaxedCutCopperBlockType {
        val e = WaxedCutCopperBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: WaxedCutCopperBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:waxed_cut_copper"

        public override val itemID: ItemID = ItemID(-351)

        private lateinit var instance7684: WaxedCutCopperBlockType

        init {
            init0()
        }

        public override val primary: WaxedCutCopperBlockType = instance7684

        public override val allInstances: List<WaxedCutCopperBlockType> = listOf(instance7684)

        public fun init0() {
            instance7684 = WaxedCutCopperBlockType(7684.toShort())
        }
    }
}
