// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class WeatheredCutCopperSlabBlockType private constructor(
    public override val runtimeID: Short,
    public val topSlotBit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(topSlotBit: Byte = this.topSlotBit): WeatheredCutCopperSlabBlockType {
        val e = WeatheredCutCopperSlabBlockType(0.toShort(), topSlotBit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: WeatheredCutCopperSlabBlockType): Boolean {
        var ret = true
        ret = ret && (this.topSlotBit == other.topSlotBit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:weathered_cut_copper_slab"

        public override val itemID: ItemID = ItemID(-363)

        private lateinit var instance7741: WeatheredCutCopperSlabBlockType

        private lateinit var instance7742: WeatheredCutCopperSlabBlockType

        init {
            init0()
        }

        public override val primary: WeatheredCutCopperSlabBlockType = instance7741

        public override val allInstances: List<WeatheredCutCopperSlabBlockType> =
            listOf(instance7741, instance7742)

        public fun init0() {
            instance7741 = WeatheredCutCopperSlabBlockType(7741.toShort(), 0.toByte())
            instance7742 = WeatheredCutCopperSlabBlockType(7742.toShort(), 1.toByte())
        }
    }
}
