// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class WebBlockType private constructor(
    public override val runtimeID: Short
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(): WebBlockType {
        val e = WebBlockType(0.toShort())
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: WebBlockType): Boolean {
        var ret = true
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:web"

        public override val itemID: ItemID = ItemID(30)

        private lateinit var instance7753: WebBlockType

        init {
            init0()
        }

        public override val primary: WebBlockType = instance7753

        public override val allInstances: List<WebBlockType> = listOf(instance7753)

        public fun init0() {
            instance7753 = WebBlockType(7753.toShort())
        }
    }
}
