// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class WheatBlockType private constructor(
    public override val runtimeID: Short,
    public val growth: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(growth: Int = this.growth): WheatBlockType {
        val e = WheatBlockType(0.toShort(), growth)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: WheatBlockType): Boolean {
        var ret = true
        ret = ret && (this.growth == other.growth)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:wheat"

        public override val itemID: ItemID = ItemID(59)

        private lateinit var instance7780: WheatBlockType

        private lateinit var instance7781: WheatBlockType

        private lateinit var instance7782: WheatBlockType

        private lateinit var instance7783: WheatBlockType

        private lateinit var instance7784: WheatBlockType

        private lateinit var instance7785: WheatBlockType

        private lateinit var instance7786: WheatBlockType

        private lateinit var instance7787: WheatBlockType

        init {
            init0()
        }

        public override val primary: WheatBlockType = instance7780

        public override val allInstances: List<WheatBlockType> =
            listOf(instance7780, instance7781, instance7782, instance7783, instance7784, instance7785, instance7786, instance7787)

        public fun init0() {
            instance7780 = WheatBlockType(7780.toShort(), 0)
            instance7781 = WheatBlockType(7781.toShort(), 1)
            instance7782 = WheatBlockType(7782.toShort(), 2)
            instance7783 = WheatBlockType(7783.toShort(), 3)
            instance7784 = WheatBlockType(7784.toShort(), 4)
            instance7785 = WheatBlockType(7785.toShort(), 5)
            instance7786 = WheatBlockType(7786.toShort(), 6)
            instance7787 = WheatBlockType(7787.toShort(), 7)
        }
    }
}
