// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class WhiteCandleBlockType private constructor(
    public override val runtimeID: Short,
    public val candles: Int,
    public val lit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(candles: Int = this.candles, lit: Byte = this.lit): WhiteCandleBlockType {
        val e = WhiteCandleBlockType(0.toShort(), candles, lit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: WhiteCandleBlockType): Boolean {
        var ret = true
        ret = ret && (this.candles == other.candles)
        ret = ret && (this.lit == other.lit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:white_candle"

        public override val itemID: ItemID = ItemID(-413)

        private lateinit var instance7788: WhiteCandleBlockType

        private lateinit var instance7789: WhiteCandleBlockType

        private lateinit var instance7790: WhiteCandleBlockType

        private lateinit var instance7791: WhiteCandleBlockType

        private lateinit var instance7792: WhiteCandleBlockType

        private lateinit var instance7793: WhiteCandleBlockType

        private lateinit var instance7794: WhiteCandleBlockType

        private lateinit var instance7795: WhiteCandleBlockType

        init {
            init0()
        }

        public override val primary: WhiteCandleBlockType = instance7788

        public override val allInstances: List<WhiteCandleBlockType> =
            listOf(instance7788, instance7789, instance7790, instance7791, instance7792, instance7793, instance7794, instance7795)

        public fun init0() {
            instance7788 = WhiteCandleBlockType(7788.toShort(), 0, 0.toByte())
            instance7789 = WhiteCandleBlockType(7789.toShort(), 1, 0.toByte())
            instance7790 = WhiteCandleBlockType(7790.toShort(), 2, 0.toByte())
            instance7791 = WhiteCandleBlockType(7791.toShort(), 3, 0.toByte())
            instance7792 = WhiteCandleBlockType(7792.toShort(), 0, 1.toByte())
            instance7793 = WhiteCandleBlockType(7793.toShort(), 1, 1.toByte())
            instance7794 = WhiteCandleBlockType(7794.toShort(), 2, 1.toByte())
            instance7795 = WhiteCandleBlockType(7795.toShort(), 3, 1.toByte())
        }
    }
}
