// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class WoodenButtonBlockType private constructor(
    public override val runtimeID: Short,
    public val buttonPressedBit: Byte,
    public val facingDirection: Int
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(
        buttonPressedBit: Byte = this.buttonPressedBit,
        facingDirection: Int =
            this.facingDirection
    ): WoodenButtonBlockType {
        val e = WoodenButtonBlockType(0.toShort(), buttonPressedBit, facingDirection)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: WoodenButtonBlockType): Boolean {
        var ret = true
        ret = ret && (this.buttonPressedBit == other.buttonPressedBit)
        ret = ret && (this.facingDirection == other.facingDirection)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:wooden_button"

        public override val itemID: ItemID = ItemID(143)

        private lateinit var instance7841: WoodenButtonBlockType

        private lateinit var instance7842: WoodenButtonBlockType

        private lateinit var instance7843: WoodenButtonBlockType

        private lateinit var instance7844: WoodenButtonBlockType

        private lateinit var instance7845: WoodenButtonBlockType

        private lateinit var instance7846: WoodenButtonBlockType

        private lateinit var instance7847: WoodenButtonBlockType

        private lateinit var instance7848: WoodenButtonBlockType

        private lateinit var instance7849: WoodenButtonBlockType

        private lateinit var instance7850: WoodenButtonBlockType

        private lateinit var instance7851: WoodenButtonBlockType

        private lateinit var instance7852: WoodenButtonBlockType

        init {
            init0()
        }

        public override val primary: WoodenButtonBlockType = instance7841

        public override val allInstances: List<WoodenButtonBlockType> =
            listOf(instance7841, instance7842, instance7843, instance7844, instance7845, instance7846, instance7847, instance7848, instance7849, instance7850, instance7851, instance7852)

        public fun init0() {
            instance7841 = WoodenButtonBlockType(7841.toShort(), 0.toByte(), 0)
            instance7842 = WoodenButtonBlockType(7842.toShort(), 0.toByte(), 1)
            instance7843 = WoodenButtonBlockType(7843.toShort(), 0.toByte(), 2)
            instance7844 = WoodenButtonBlockType(7844.toShort(), 0.toByte(), 3)
            instance7845 = WoodenButtonBlockType(7845.toShort(), 0.toByte(), 4)
            instance7846 = WoodenButtonBlockType(7846.toShort(), 0.toByte(), 5)
            instance7847 = WoodenButtonBlockType(7847.toShort(), 1.toByte(), 0)
            instance7848 = WoodenButtonBlockType(7848.toShort(), 1.toByte(), 1)
            instance7849 = WoodenButtonBlockType(7849.toShort(), 1.toByte(), 2)
            instance7850 = WoodenButtonBlockType(7850.toShort(), 1.toByte(), 3)
            instance7851 = WoodenButtonBlockType(7851.toShort(), 1.toByte(), 4)
            instance7852 = WoodenButtonBlockType(7852.toShort(), 1.toByte(), 5)
        }
    }
}
