// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.blocks

import com.github.bedrockecs.vanilla.`data`.items.ItemID
import kotlinx.serialization.Serializable
import kotlin.Boolean
import kotlin.Byte
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

@Serializable
public data class YellowCandleCakeBlockType private constructor(
    public override val runtimeID: Short,
    public val lit: Byte
) : VanillaBlockType {
    public override val blockType: String = Companion.blockType

    public fun with(lit: Byte = this.lit): YellowCandleCakeBlockType {
        val e = YellowCandleCakeBlockType(0.toShort(), lit)
        return allInstances.find { it.compareVariantProperties(e) }!!
    }

    @Suppress("UNUSED_PARAMETER")
    public fun compareVariantProperties(other: YellowCandleCakeBlockType): Boolean {
        var ret = true
        ret = ret && (this.lit == other.lit)
        return ret
    }

    public companion object : VanillaBlockType.ICompanion {
        public override val blockType: String = "minecraft:yellow_candle_cake"

        public override val itemID: ItemID = ItemID(-434)

        private lateinit var instance7937: YellowCandleCakeBlockType

        private lateinit var instance7938: YellowCandleCakeBlockType

        init {
            init0()
        }

        public override val primary: YellowCandleCakeBlockType = instance7937

        public override val allInstances: List<YellowCandleCakeBlockType> =
            listOf(instance7937, instance7938)

        public fun init0() {
            instance7937 = YellowCandleCakeBlockType(7937.toShort(), 0.toByte())
            instance7938 = YellowCandleCakeBlockType(7938.toShort(), 1.toByte())
        }
    }
}
