// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.items

import kotlinx.serialization.Serializable
import kotlin.String

@Serializable
public class DragonBreathItemType : VanillaItemType {
    public override val itemType: String = Companion.itemType

    public override fun clone(): DragonBreathItemType = this

    public companion object : VanillaItemType.ICompanion {
        public override val itemID: ItemID = ItemID(560)

        public override val itemType: String = "minecraft:dragon_breath"
    }
}
