// generated by becs datacompiler, DO NOT EDIT!
package com.github.bedrockecs.vanilla.`data`.items

import kotlinx.serialization.Serializable
import kotlin.String

@Serializable
public class MusicDiscCatItemType : VanillaItemType {
    public override val itemType: String = Companion.itemType

    public override fun clone(): MusicDiscCatItemType = this

    public companion object : VanillaItemType.ICompanion {
        public override val itemID: ItemID = ItemID(535)

        public override val itemType: String = "minecraft:music_disc_cat"
    }
}
